logging:
  config: classpath:logback-spring.xml
spring:
  datasource:
    url: jdbc:mysql://10.50.0.204:3306?useSSL=false
#    url: jdbc:mysql://192.168.0.113:3306?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
#    启用druid，详细配置见DataSourceConfiguration
#    type: com.alibaba.druid.pool.DruidDataSource
  redis:
#    host: 192.168.0.113
    host: 10.50.0.204
    password: 123456
    port: 6379
    pool:
      max-active: 10
    timeout: 10000
xplat:
  jooq:
    max-select-rows: 1000

