/*
 * This file is generated by jOOQ.
*/
package com.chenqiguang.springboot.domain.jooq;


import com.chenqiguang.springboot.domain.jooq.tables.TSettlement;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Chenqiguang extends SchemaImpl {

    private static final long serialVersionUID = 348282841;

    /**
     * The reference instance of <code>chenqiguang</code>
     */
    public static final Chenqiguang CHENQIGUANG = new Chenqiguang();

    /**
     * 结算单表
     */
    public final TSettlement T_SETTLEMENT = com.chenqiguang.springboot.domain.jooq.tables.TSettlement.T_SETTLEMENT;

    /**
     * No further instances allowed
     */
    private Chenqiguang() {
        super("chenqiguang", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            TSettlement.T_SETTLEMENT);
    }
}
