/*
 * This file is generated by jOOQ.
*/
package com.chenqiguang.springboot.domain.jooq;


import com.chenqiguang.springboot.domain.jooq.tables.TSettlement;
import com.chenqiguang.springboot.domain.jooq.tables.records.TSettlementRecord;

import javax.annotation.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>chenqiguang</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<TSettlementRecord> KEY_T_SETTLEMENT_PRIMARY = UniqueKeys0.KEY_T_SETTLEMENT_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<TSettlementRecord> KEY_T_SETTLEMENT_PRIMARY = createUniqueKey(TSettlement.T_SETTLEMENT, "KEY_t_settlement_PRIMARY", TSettlement.T_SETTLEMENT.SETTLEMENT_ID);
    }
}
