/*
 * This file is generated by jOOQ.
*/
package com.chenqiguang.springboot.domain.jooq;


import com.chenqiguang.springboot.domain.jooq.tables.TSettlement;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in chenqiguang
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 结算单表
     */
    public static final TSettlement T_SETTLEMENT = com.chenqiguang.springboot.domain.jooq.tables.TSettlement.T_SETTLEMENT;
}
