/*
 * This file is generated by jOOQ.
*/
package com.chenqiguang.springboot.domain.jooq.tables.pojos;


import com.chenqiguang.springboot.domain.stratrgy.DomainBase;

import java.io.Serializable;
import java.math.BigDecimal;

import javax.annotation.Generated;


/**
 * 结算单表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TSettlementObj extends DomainBase implements Serializable {

    private static final long serialVersionUID = 214113178;

    private String     settlementId;
    private String     settlementNo;
    private Long       ruleId;
    private String     settlementPeriod;
    private String     businessBillType;
    private String     invoiceType;
    private String     accordingRule;
    private String     predictInvoiceDate;
    private String     sellerTenantCode;
    private String     sellerNoAr;
    private String     sellerNo;
    private String     sellerCode;
    private String     sellerTaxNo;
    private String     sellerName;
    private String     sellerAddress;
    private String     sellerTel;
    private String     sellerBankName;
    private String     sellerBankAccount;
    private String     purchaserTenantCode;
    private String     purchaserNo;
    private String     purchaserNoAr;
    private String     purchaserCode;
    private String     purchaserTaxNo;
    private String     purchaserName;
    private String     purchaserAddress;
    private String     purchaserTel;
    private String     purchaserBankName;
    private String     purchaserBankAccount;
    private Integer    purchaserInvoiceInfoId;
    private Integer    sellerInvoiceInfoId;
    private BigDecimal perinvoiceAmountLimit;
    private String     otherPlatAccount;
    private String     customBillType;
    private BigDecimal amountWithoutTax;
    private BigDecimal taxAmount;
    private BigDecimal amountWithTax;
    private BigDecimal canMakeInvoiceAmountWithTax;
    private BigDecimal alreadyInvoiceAmountWithTax;
    private BigDecimal alreadyAuthAmountWithTax;
    private BigDecimal canMakeInvoiceAmountWithoutTax;
    private BigDecimal alreadyInvoiceAmountWithoutTax;
    private BigDecimal alreadyAuthAmountWithoutTax;
    private BigDecimal canMakeInvoiceTaxAmount;
    private BigDecimal alreadyInvoiceTaxAmount;
    private BigDecimal alreadyAuthTaxAmount;
    private BigDecimal alreadyPayTaxAmount;
    private BigDecimal alreadyPayAmountWithoutTax;
    private BigDecimal alreadyPayAmountWihtTax;
    private BigDecimal alreadyDeposeAmountWithTax;
    private BigDecimal alreadyRedAmountWithTax;
    private BigDecimal discountWithoutTax;
    private BigDecimal discountTax;
    private BigDecimal discountWithTax;
    private String     remark;
    private String     appendRemark;
    private Integer    preInvoiceNums;
    private Integer    canMakeInvoiceNums;
    private Integer    invoiceNums;
    private String     receiveConfirmFlag;
    private String     uploadConfirmFlag;
    private String     status;
    private String     originInvoiceNo;
    private String     originInvoiceCode;
    private String     redNotificationNo;
    private String     orderNo;
    private String     contractNo;
    private String     systemOrig;
    private String     salesBillNo;
    private String     isNeedAuth;
    private String     cooperateFlag;
    private String     requestSerialNo;
    private String     purchaserEmail;
    private String     logisticsStatus;
    private String     createTime;
    private String     createUserId;
    private String     updateTime;
    private String     updateUserId;
    private String     specialExt1;
    private String     specialExt2;
    private String     ext1;
    private String     ext2;
    private String     ext3;
    private String     ext4;
    private String     ext5;
    private String     ext6;
    private String     ext7;
    private String     ext8;
    private String     ext9;
    private String     ext10;
    private String     uploadWay;
    private String     cashierName;
    private String     checkerName;
    private String     invoicerName;
    private String     lockFlag;
    private String     taxRate;
    private String     useingStatus;
    private BigDecimal purAlreadyAmountWithoutTax;
    private BigDecimal purAlreadyTaxAmount;
    private BigDecimal purAlreadyAmountWithTax;
    private String     printContentFlag;
    private Integer    sellerInvoicePersonInfoId;
    private String     purMachStatus;
    private String     reciveUser;

    public TSettlementObj() {}

    public TSettlementObj(TSettlementObj value) {
        this.settlementId = value.settlementId;
        this.settlementNo = value.settlementNo;
        this.ruleId = value.ruleId;
        this.settlementPeriod = value.settlementPeriod;
        this.businessBillType = value.businessBillType;
        this.invoiceType = value.invoiceType;
        this.accordingRule = value.accordingRule;
        this.predictInvoiceDate = value.predictInvoiceDate;
        this.sellerTenantCode = value.sellerTenantCode;
        this.sellerNoAr = value.sellerNoAr;
        this.sellerNo = value.sellerNo;
        this.sellerCode = value.sellerCode;
        this.sellerTaxNo = value.sellerTaxNo;
        this.sellerName = value.sellerName;
        this.sellerAddress = value.sellerAddress;
        this.sellerTel = value.sellerTel;
        this.sellerBankName = value.sellerBankName;
        this.sellerBankAccount = value.sellerBankAccount;
        this.purchaserTenantCode = value.purchaserTenantCode;
        this.purchaserNo = value.purchaserNo;
        this.purchaserNoAr = value.purchaserNoAr;
        this.purchaserCode = value.purchaserCode;
        this.purchaserTaxNo = value.purchaserTaxNo;
        this.purchaserName = value.purchaserName;
        this.purchaserAddress = value.purchaserAddress;
        this.purchaserTel = value.purchaserTel;
        this.purchaserBankName = value.purchaserBankName;
        this.purchaserBankAccount = value.purchaserBankAccount;
        this.purchaserInvoiceInfoId = value.purchaserInvoiceInfoId;
        this.sellerInvoiceInfoId = value.sellerInvoiceInfoId;
        this.perinvoiceAmountLimit = value.perinvoiceAmountLimit;
        this.otherPlatAccount = value.otherPlatAccount;
        this.customBillType = value.customBillType;
        this.amountWithoutTax = value.amountWithoutTax;
        this.taxAmount = value.taxAmount;
        this.amountWithTax = value.amountWithTax;
        this.canMakeInvoiceAmountWithTax = value.canMakeInvoiceAmountWithTax;
        this.alreadyInvoiceAmountWithTax = value.alreadyInvoiceAmountWithTax;
        this.alreadyAuthAmountWithTax = value.alreadyAuthAmountWithTax;
        this.canMakeInvoiceAmountWithoutTax = value.canMakeInvoiceAmountWithoutTax;
        this.alreadyInvoiceAmountWithoutTax = value.alreadyInvoiceAmountWithoutTax;
        this.alreadyAuthAmountWithoutTax = value.alreadyAuthAmountWithoutTax;
        this.canMakeInvoiceTaxAmount = value.canMakeInvoiceTaxAmount;
        this.alreadyInvoiceTaxAmount = value.alreadyInvoiceTaxAmount;
        this.alreadyAuthTaxAmount = value.alreadyAuthTaxAmount;
        this.alreadyPayTaxAmount = value.alreadyPayTaxAmount;
        this.alreadyPayAmountWithoutTax = value.alreadyPayAmountWithoutTax;
        this.alreadyPayAmountWihtTax = value.alreadyPayAmountWihtTax;
        this.alreadyDeposeAmountWithTax = value.alreadyDeposeAmountWithTax;
        this.alreadyRedAmountWithTax = value.alreadyRedAmountWithTax;
        this.discountWithoutTax = value.discountWithoutTax;
        this.discountTax = value.discountTax;
        this.discountWithTax = value.discountWithTax;
        this.remark = value.remark;
        this.appendRemark = value.appendRemark;
        this.preInvoiceNums = value.preInvoiceNums;
        this.canMakeInvoiceNums = value.canMakeInvoiceNums;
        this.invoiceNums = value.invoiceNums;
        this.receiveConfirmFlag = value.receiveConfirmFlag;
        this.uploadConfirmFlag = value.uploadConfirmFlag;
        this.status = value.status;
        this.originInvoiceNo = value.originInvoiceNo;
        this.originInvoiceCode = value.originInvoiceCode;
        this.redNotificationNo = value.redNotificationNo;
        this.orderNo = value.orderNo;
        this.contractNo = value.contractNo;
        this.systemOrig = value.systemOrig;
        this.salesBillNo = value.salesBillNo;
        this.isNeedAuth = value.isNeedAuth;
        this.cooperateFlag = value.cooperateFlag;
        this.requestSerialNo = value.requestSerialNo;
        this.purchaserEmail = value.purchaserEmail;
        this.logisticsStatus = value.logisticsStatus;
        this.createTime = value.createTime;
        this.createUserId = value.createUserId;
        this.updateTime = value.updateTime;
        this.updateUserId = value.updateUserId;
        this.specialExt1 = value.specialExt1;
        this.specialExt2 = value.specialExt2;
        this.ext1 = value.ext1;
        this.ext2 = value.ext2;
        this.ext3 = value.ext3;
        this.ext4 = value.ext4;
        this.ext5 = value.ext5;
        this.ext6 = value.ext6;
        this.ext7 = value.ext7;
        this.ext8 = value.ext8;
        this.ext9 = value.ext9;
        this.ext10 = value.ext10;
        this.uploadWay = value.uploadWay;
        this.cashierName = value.cashierName;
        this.checkerName = value.checkerName;
        this.invoicerName = value.invoicerName;
        this.lockFlag = value.lockFlag;
        this.taxRate = value.taxRate;
        this.useingStatus = value.useingStatus;
        this.purAlreadyAmountWithoutTax = value.purAlreadyAmountWithoutTax;
        this.purAlreadyTaxAmount = value.purAlreadyTaxAmount;
        this.purAlreadyAmountWithTax = value.purAlreadyAmountWithTax;
        this.printContentFlag = value.printContentFlag;
        this.sellerInvoicePersonInfoId = value.sellerInvoicePersonInfoId;
        this.purMachStatus = value.purMachStatus;
        this.reciveUser = value.reciveUser;
    }

    public TSettlementObj(
        String     settlementId,
        String     settlementNo,
        Long       ruleId,
        String     settlementPeriod,
        String     businessBillType,
        String     invoiceType,
        String     accordingRule,
        String     predictInvoiceDate,
        String     sellerTenantCode,
        String     sellerNoAr,
        String     sellerNo,
        String     sellerCode,
        String     sellerTaxNo,
        String     sellerName,
        String     sellerAddress,
        String     sellerTel,
        String     sellerBankName,
        String     sellerBankAccount,
        String     purchaserTenantCode,
        String     purchaserNo,
        String     purchaserNoAr,
        String     purchaserCode,
        String     purchaserTaxNo,
        String     purchaserName,
        String     purchaserAddress,
        String     purchaserTel,
        String     purchaserBankName,
        String     purchaserBankAccount,
        Integer    purchaserInvoiceInfoId,
        Integer    sellerInvoiceInfoId,
        BigDecimal perinvoiceAmountLimit,
        String     otherPlatAccount,
        String     customBillType,
        BigDecimal amountWithoutTax,
        BigDecimal taxAmount,
        BigDecimal amountWithTax,
        BigDecimal canMakeInvoiceAmountWithTax,
        BigDecimal alreadyInvoiceAmountWithTax,
        BigDecimal alreadyAuthAmountWithTax,
        BigDecimal canMakeInvoiceAmountWithoutTax,
        BigDecimal alreadyInvoiceAmountWithoutTax,
        BigDecimal alreadyAuthAmountWithoutTax,
        BigDecimal canMakeInvoiceTaxAmount,
        BigDecimal alreadyInvoiceTaxAmount,
        BigDecimal alreadyAuthTaxAmount,
        BigDecimal alreadyPayTaxAmount,
        BigDecimal alreadyPayAmountWithoutTax,
        BigDecimal alreadyPayAmountWihtTax,
        BigDecimal alreadyDeposeAmountWithTax,
        BigDecimal alreadyRedAmountWithTax,
        BigDecimal discountWithoutTax,
        BigDecimal discountTax,
        BigDecimal discountWithTax,
        String     remark,
        String     appendRemark,
        Integer    preInvoiceNums,
        Integer    canMakeInvoiceNums,
        Integer    invoiceNums,
        String     receiveConfirmFlag,
        String     uploadConfirmFlag,
        String     status,
        String     originInvoiceNo,
        String     originInvoiceCode,
        String     redNotificationNo,
        String     orderNo,
        String     contractNo,
        String     systemOrig,
        String     salesBillNo,
        String     isNeedAuth,
        String     cooperateFlag,
        String     requestSerialNo,
        String     purchaserEmail,
        String     logisticsStatus,
        String     createTime,
        String     createUserId,
        String     updateTime,
        String     updateUserId,
        String     specialExt1,
        String     specialExt2,
        String     ext1,
        String     ext2,
        String     ext3,
        String     ext4,
        String     ext5,
        String     ext6,
        String     ext7,
        String     ext8,
        String     ext9,
        String     ext10,
        String     uploadWay,
        String     cashierName,
        String     checkerName,
        String     invoicerName,
        String     lockFlag,
        String     taxRate,
        String     useingStatus,
        BigDecimal purAlreadyAmountWithoutTax,
        BigDecimal purAlreadyTaxAmount,
        BigDecimal purAlreadyAmountWithTax,
        String     printContentFlag,
        Integer    sellerInvoicePersonInfoId,
        String     purMachStatus,
        String     reciveUser
    ) {
        this.settlementId = settlementId;
        this.settlementNo = settlementNo;
        this.ruleId = ruleId;
        this.settlementPeriod = settlementPeriod;
        this.businessBillType = businessBillType;
        this.invoiceType = invoiceType;
        this.accordingRule = accordingRule;
        this.predictInvoiceDate = predictInvoiceDate;
        this.sellerTenantCode = sellerTenantCode;
        this.sellerNoAr = sellerNoAr;
        this.sellerNo = sellerNo;
        this.sellerCode = sellerCode;
        this.sellerTaxNo = sellerTaxNo;
        this.sellerName = sellerName;
        this.sellerAddress = sellerAddress;
        this.sellerTel = sellerTel;
        this.sellerBankName = sellerBankName;
        this.sellerBankAccount = sellerBankAccount;
        this.purchaserTenantCode = purchaserTenantCode;
        this.purchaserNo = purchaserNo;
        this.purchaserNoAr = purchaserNoAr;
        this.purchaserCode = purchaserCode;
        this.purchaserTaxNo = purchaserTaxNo;
        this.purchaserName = purchaserName;
        this.purchaserAddress = purchaserAddress;
        this.purchaserTel = purchaserTel;
        this.purchaserBankName = purchaserBankName;
        this.purchaserBankAccount = purchaserBankAccount;
        this.purchaserInvoiceInfoId = purchaserInvoiceInfoId;
        this.sellerInvoiceInfoId = sellerInvoiceInfoId;
        this.perinvoiceAmountLimit = perinvoiceAmountLimit;
        this.otherPlatAccount = otherPlatAccount;
        this.customBillType = customBillType;
        this.amountWithoutTax = amountWithoutTax;
        this.taxAmount = taxAmount;
        this.amountWithTax = amountWithTax;
        this.canMakeInvoiceAmountWithTax = canMakeInvoiceAmountWithTax;
        this.alreadyInvoiceAmountWithTax = alreadyInvoiceAmountWithTax;
        this.alreadyAuthAmountWithTax = alreadyAuthAmountWithTax;
        this.canMakeInvoiceAmountWithoutTax = canMakeInvoiceAmountWithoutTax;
        this.alreadyInvoiceAmountWithoutTax = alreadyInvoiceAmountWithoutTax;
        this.alreadyAuthAmountWithoutTax = alreadyAuthAmountWithoutTax;
        this.canMakeInvoiceTaxAmount = canMakeInvoiceTaxAmount;
        this.alreadyInvoiceTaxAmount = alreadyInvoiceTaxAmount;
        this.alreadyAuthTaxAmount = alreadyAuthTaxAmount;
        this.alreadyPayTaxAmount = alreadyPayTaxAmount;
        this.alreadyPayAmountWithoutTax = alreadyPayAmountWithoutTax;
        this.alreadyPayAmountWihtTax = alreadyPayAmountWihtTax;
        this.alreadyDeposeAmountWithTax = alreadyDeposeAmountWithTax;
        this.alreadyRedAmountWithTax = alreadyRedAmountWithTax;
        this.discountWithoutTax = discountWithoutTax;
        this.discountTax = discountTax;
        this.discountWithTax = discountWithTax;
        this.remark = remark;
        this.appendRemark = appendRemark;
        this.preInvoiceNums = preInvoiceNums;
        this.canMakeInvoiceNums = canMakeInvoiceNums;
        this.invoiceNums = invoiceNums;
        this.receiveConfirmFlag = receiveConfirmFlag;
        this.uploadConfirmFlag = uploadConfirmFlag;
        this.status = status;
        this.originInvoiceNo = originInvoiceNo;
        this.originInvoiceCode = originInvoiceCode;
        this.redNotificationNo = redNotificationNo;
        this.orderNo = orderNo;
        this.contractNo = contractNo;
        this.systemOrig = systemOrig;
        this.salesBillNo = salesBillNo;
        this.isNeedAuth = isNeedAuth;
        this.cooperateFlag = cooperateFlag;
        this.requestSerialNo = requestSerialNo;
        this.purchaserEmail = purchaserEmail;
        this.logisticsStatus = logisticsStatus;
        this.createTime = createTime;
        this.createUserId = createUserId;
        this.updateTime = updateTime;
        this.updateUserId = updateUserId;
        this.specialExt1 = specialExt1;
        this.specialExt2 = specialExt2;
        this.ext1 = ext1;
        this.ext2 = ext2;
        this.ext3 = ext3;
        this.ext4 = ext4;
        this.ext5 = ext5;
        this.ext6 = ext6;
        this.ext7 = ext7;
        this.ext8 = ext8;
        this.ext9 = ext9;
        this.ext10 = ext10;
        this.uploadWay = uploadWay;
        this.cashierName = cashierName;
        this.checkerName = checkerName;
        this.invoicerName = invoicerName;
        this.lockFlag = lockFlag;
        this.taxRate = taxRate;
        this.useingStatus = useingStatus;
        this.purAlreadyAmountWithoutTax = purAlreadyAmountWithoutTax;
        this.purAlreadyTaxAmount = purAlreadyTaxAmount;
        this.purAlreadyAmountWithTax = purAlreadyAmountWithTax;
        this.printContentFlag = printContentFlag;
        this.sellerInvoicePersonInfoId = sellerInvoicePersonInfoId;
        this.purMachStatus = purMachStatus;
        this.reciveUser = reciveUser;
    }

    public String getSettlementId() {
        return this.settlementId;
    }

    public void setSettlementId(String settlementId) {
        this.settlementId = settlementId;
    }

    public String getSettlementNo() {
        return this.settlementNo;
    }

    public void setSettlementNo(String settlementNo) {
        this.settlementNo = settlementNo;
    }

    public Long getRuleId() {
        return this.ruleId;
    }

    public void setRuleId(Long ruleId) {
        this.ruleId = ruleId;
    }

    public String getSettlementPeriod() {
        return this.settlementPeriod;
    }

    public void setSettlementPeriod(String settlementPeriod) {
        this.settlementPeriod = settlementPeriod;
    }

    public String getBusinessBillType() {
        return this.businessBillType;
    }

    public void setBusinessBillType(String businessBillType) {
        this.businessBillType = businessBillType;
    }

    public String getInvoiceType() {
        return this.invoiceType;
    }

    public void setInvoiceType(String invoiceType) {
        this.invoiceType = invoiceType;
    }

    public String getAccordingRule() {
        return this.accordingRule;
    }

    public void setAccordingRule(String accordingRule) {
        this.accordingRule = accordingRule;
    }

    public String getPredictInvoiceDate() {
        return this.predictInvoiceDate;
    }

    public void setPredictInvoiceDate(String predictInvoiceDate) {
        this.predictInvoiceDate = predictInvoiceDate;
    }

    public String getSellerTenantCode() {
        return this.sellerTenantCode;
    }

    public void setSellerTenantCode(String sellerTenantCode) {
        this.sellerTenantCode = sellerTenantCode;
    }

    public String getSellerNoAr() {
        return this.sellerNoAr;
    }

    public void setSellerNoAr(String sellerNoAr) {
        this.sellerNoAr = sellerNoAr;
    }

    public String getSellerNo() {
        return this.sellerNo;
    }

    public void setSellerNo(String sellerNo) {
        this.sellerNo = sellerNo;
    }

    public String getSellerCode() {
        return this.sellerCode;
    }

    public void setSellerCode(String sellerCode) {
        this.sellerCode = sellerCode;
    }

    public String getSellerTaxNo() {
        return this.sellerTaxNo;
    }

    public void setSellerTaxNo(String sellerTaxNo) {
        this.sellerTaxNo = sellerTaxNo;
    }

    public String getSellerName() {
        return this.sellerName;
    }

    public void setSellerName(String sellerName) {
        this.sellerName = sellerName;
    }

    public String getSellerAddress() {
        return this.sellerAddress;
    }

    public void setSellerAddress(String sellerAddress) {
        this.sellerAddress = sellerAddress;
    }

    public String getSellerTel() {
        return this.sellerTel;
    }

    public void setSellerTel(String sellerTel) {
        this.sellerTel = sellerTel;
    }

    public String getSellerBankName() {
        return this.sellerBankName;
    }

    public void setSellerBankName(String sellerBankName) {
        this.sellerBankName = sellerBankName;
    }

    public String getSellerBankAccount() {
        return this.sellerBankAccount;
    }

    public void setSellerBankAccount(String sellerBankAccount) {
        this.sellerBankAccount = sellerBankAccount;
    }

    public String getPurchaserTenantCode() {
        return this.purchaserTenantCode;
    }

    public void setPurchaserTenantCode(String purchaserTenantCode) {
        this.purchaserTenantCode = purchaserTenantCode;
    }

    public String getPurchaserNo() {
        return this.purchaserNo;
    }

    public void setPurchaserNo(String purchaserNo) {
        this.purchaserNo = purchaserNo;
    }

    public String getPurchaserNoAr() {
        return this.purchaserNoAr;
    }

    public void setPurchaserNoAr(String purchaserNoAr) {
        this.purchaserNoAr = purchaserNoAr;
    }

    public String getPurchaserCode() {
        return this.purchaserCode;
    }

    public void setPurchaserCode(String purchaserCode) {
        this.purchaserCode = purchaserCode;
    }

    public String getPurchaserTaxNo() {
        return this.purchaserTaxNo;
    }

    public void setPurchaserTaxNo(String purchaserTaxNo) {
        this.purchaserTaxNo = purchaserTaxNo;
    }

    public String getPurchaserName() {
        return this.purchaserName;
    }

    public void setPurchaserName(String purchaserName) {
        this.purchaserName = purchaserName;
    }

    public String getPurchaserAddress() {
        return this.purchaserAddress;
    }

    public void setPurchaserAddress(String purchaserAddress) {
        this.purchaserAddress = purchaserAddress;
    }

    public String getPurchaserTel() {
        return this.purchaserTel;
    }

    public void setPurchaserTel(String purchaserTel) {
        this.purchaserTel = purchaserTel;
    }

    public String getPurchaserBankName() {
        return this.purchaserBankName;
    }

    public void setPurchaserBankName(String purchaserBankName) {
        this.purchaserBankName = purchaserBankName;
    }

    public String getPurchaserBankAccount() {
        return this.purchaserBankAccount;
    }

    public void setPurchaserBankAccount(String purchaserBankAccount) {
        this.purchaserBankAccount = purchaserBankAccount;
    }

    public Integer getPurchaserInvoiceInfoId() {
        return this.purchaserInvoiceInfoId;
    }

    public void setPurchaserInvoiceInfoId(Integer purchaserInvoiceInfoId) {
        this.purchaserInvoiceInfoId = purchaserInvoiceInfoId;
    }

    public Integer getSellerInvoiceInfoId() {
        return this.sellerInvoiceInfoId;
    }

    public void setSellerInvoiceInfoId(Integer sellerInvoiceInfoId) {
        this.sellerInvoiceInfoId = sellerInvoiceInfoId;
    }

    public BigDecimal getPerinvoiceAmountLimit() {
        return this.perinvoiceAmountLimit;
    }

    public void setPerinvoiceAmountLimit(BigDecimal perinvoiceAmountLimit) {
        this.perinvoiceAmountLimit = perinvoiceAmountLimit;
    }

    public String getOtherPlatAccount() {
        return this.otherPlatAccount;
    }

    public void setOtherPlatAccount(String otherPlatAccount) {
        this.otherPlatAccount = otherPlatAccount;
    }

    public String getCustomBillType() {
        return this.customBillType;
    }

    public void setCustomBillType(String customBillType) {
        this.customBillType = customBillType;
    }

    public BigDecimal getAmountWithoutTax() {
        return this.amountWithoutTax;
    }

    public void setAmountWithoutTax(BigDecimal amountWithoutTax) {
        this.amountWithoutTax = amountWithoutTax;
    }

    public BigDecimal getTaxAmount() {
        return this.taxAmount;
    }

    public void setTaxAmount(BigDecimal taxAmount) {
        this.taxAmount = taxAmount;
    }

    public BigDecimal getAmountWithTax() {
        return this.amountWithTax;
    }

    public void setAmountWithTax(BigDecimal amountWithTax) {
        this.amountWithTax = amountWithTax;
    }

    public BigDecimal getCanMakeInvoiceAmountWithTax() {
        return this.canMakeInvoiceAmountWithTax;
    }

    public void setCanMakeInvoiceAmountWithTax(BigDecimal canMakeInvoiceAmountWithTax) {
        this.canMakeInvoiceAmountWithTax = canMakeInvoiceAmountWithTax;
    }

    public BigDecimal getAlreadyInvoiceAmountWithTax() {
        return this.alreadyInvoiceAmountWithTax;
    }

    public void setAlreadyInvoiceAmountWithTax(BigDecimal alreadyInvoiceAmountWithTax) {
        this.alreadyInvoiceAmountWithTax = alreadyInvoiceAmountWithTax;
    }

    public BigDecimal getAlreadyAuthAmountWithTax() {
        return this.alreadyAuthAmountWithTax;
    }

    public void setAlreadyAuthAmountWithTax(BigDecimal alreadyAuthAmountWithTax) {
        this.alreadyAuthAmountWithTax = alreadyAuthAmountWithTax;
    }

    public BigDecimal getCanMakeInvoiceAmountWithoutTax() {
        return this.canMakeInvoiceAmountWithoutTax;
    }

    public void setCanMakeInvoiceAmountWithoutTax(BigDecimal canMakeInvoiceAmountWithoutTax) {
        this.canMakeInvoiceAmountWithoutTax = canMakeInvoiceAmountWithoutTax;
    }

    public BigDecimal getAlreadyInvoiceAmountWithoutTax() {
        return this.alreadyInvoiceAmountWithoutTax;
    }

    public void setAlreadyInvoiceAmountWithoutTax(BigDecimal alreadyInvoiceAmountWithoutTax) {
        this.alreadyInvoiceAmountWithoutTax = alreadyInvoiceAmountWithoutTax;
    }

    public BigDecimal getAlreadyAuthAmountWithoutTax() {
        return this.alreadyAuthAmountWithoutTax;
    }

    public void setAlreadyAuthAmountWithoutTax(BigDecimal alreadyAuthAmountWithoutTax) {
        this.alreadyAuthAmountWithoutTax = alreadyAuthAmountWithoutTax;
    }

    public BigDecimal getCanMakeInvoiceTaxAmount() {
        return this.canMakeInvoiceTaxAmount;
    }

    public void setCanMakeInvoiceTaxAmount(BigDecimal canMakeInvoiceTaxAmount) {
        this.canMakeInvoiceTaxAmount = canMakeInvoiceTaxAmount;
    }

    public BigDecimal getAlreadyInvoiceTaxAmount() {
        return this.alreadyInvoiceTaxAmount;
    }

    public void setAlreadyInvoiceTaxAmount(BigDecimal alreadyInvoiceTaxAmount) {
        this.alreadyInvoiceTaxAmount = alreadyInvoiceTaxAmount;
    }

    public BigDecimal getAlreadyAuthTaxAmount() {
        return this.alreadyAuthTaxAmount;
    }

    public void setAlreadyAuthTaxAmount(BigDecimal alreadyAuthTaxAmount) {
        this.alreadyAuthTaxAmount = alreadyAuthTaxAmount;
    }

    public BigDecimal getAlreadyPayTaxAmount() {
        return this.alreadyPayTaxAmount;
    }

    public void setAlreadyPayTaxAmount(BigDecimal alreadyPayTaxAmount) {
        this.alreadyPayTaxAmount = alreadyPayTaxAmount;
    }

    public BigDecimal getAlreadyPayAmountWithoutTax() {
        return this.alreadyPayAmountWithoutTax;
    }

    public void setAlreadyPayAmountWithoutTax(BigDecimal alreadyPayAmountWithoutTax) {
        this.alreadyPayAmountWithoutTax = alreadyPayAmountWithoutTax;
    }

    public BigDecimal getAlreadyPayAmountWihtTax() {
        return this.alreadyPayAmountWihtTax;
    }

    public void setAlreadyPayAmountWihtTax(BigDecimal alreadyPayAmountWihtTax) {
        this.alreadyPayAmountWihtTax = alreadyPayAmountWihtTax;
    }

    public BigDecimal getAlreadyDeposeAmountWithTax() {
        return this.alreadyDeposeAmountWithTax;
    }

    public void setAlreadyDeposeAmountWithTax(BigDecimal alreadyDeposeAmountWithTax) {
        this.alreadyDeposeAmountWithTax = alreadyDeposeAmountWithTax;
    }

    public BigDecimal getAlreadyRedAmountWithTax() {
        return this.alreadyRedAmountWithTax;
    }

    public void setAlreadyRedAmountWithTax(BigDecimal alreadyRedAmountWithTax) {
        this.alreadyRedAmountWithTax = alreadyRedAmountWithTax;
    }

    public BigDecimal getDiscountWithoutTax() {
        return this.discountWithoutTax;
    }

    public void setDiscountWithoutTax(BigDecimal discountWithoutTax) {
        this.discountWithoutTax = discountWithoutTax;
    }

    public BigDecimal getDiscountTax() {
        return this.discountTax;
    }

    public void setDiscountTax(BigDecimal discountTax) {
        this.discountTax = discountTax;
    }

    public BigDecimal getDiscountWithTax() {
        return this.discountWithTax;
    }

    public void setDiscountWithTax(BigDecimal discountWithTax) {
        this.discountWithTax = discountWithTax;
    }

    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getAppendRemark() {
        return this.appendRemark;
    }

    public void setAppendRemark(String appendRemark) {
        this.appendRemark = appendRemark;
    }

    public Integer getPreInvoiceNums() {
        return this.preInvoiceNums;
    }

    public void setPreInvoiceNums(Integer preInvoiceNums) {
        this.preInvoiceNums = preInvoiceNums;
    }

    public Integer getCanMakeInvoiceNums() {
        return this.canMakeInvoiceNums;
    }

    public void setCanMakeInvoiceNums(Integer canMakeInvoiceNums) {
        this.canMakeInvoiceNums = canMakeInvoiceNums;
    }

    public Integer getInvoiceNums() {
        return this.invoiceNums;
    }

    public void setInvoiceNums(Integer invoiceNums) {
        this.invoiceNums = invoiceNums;
    }

    public String getReceiveConfirmFlag() {
        return this.receiveConfirmFlag;
    }

    public void setReceiveConfirmFlag(String receiveConfirmFlag) {
        this.receiveConfirmFlag = receiveConfirmFlag;
    }

    public String getUploadConfirmFlag() {
        return this.uploadConfirmFlag;
    }

    public void setUploadConfirmFlag(String uploadConfirmFlag) {
        this.uploadConfirmFlag = uploadConfirmFlag;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getOriginInvoiceNo() {
        return this.originInvoiceNo;
    }

    public void setOriginInvoiceNo(String originInvoiceNo) {
        this.originInvoiceNo = originInvoiceNo;
    }

    public String getOriginInvoiceCode() {
        return this.originInvoiceCode;
    }

    public void setOriginInvoiceCode(String originInvoiceCode) {
        this.originInvoiceCode = originInvoiceCode;
    }

    public String getRedNotificationNo() {
        return this.redNotificationNo;
    }

    public void setRedNotificationNo(String redNotificationNo) {
        this.redNotificationNo = redNotificationNo;
    }

    public String getOrderNo() {
        return this.orderNo;
    }

    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    public String getContractNo() {
        return this.contractNo;
    }

    public void setContractNo(String contractNo) {
        this.contractNo = contractNo;
    }

    public String getSystemOrig() {
        return this.systemOrig;
    }

    public void setSystemOrig(String systemOrig) {
        this.systemOrig = systemOrig;
    }

    public String getSalesBillNo() {
        return this.salesBillNo;
    }

    public void setSalesBillNo(String salesBillNo) {
        this.salesBillNo = salesBillNo;
    }

    public String getIsNeedAuth() {
        return this.isNeedAuth;
    }

    public void setIsNeedAuth(String isNeedAuth) {
        this.isNeedAuth = isNeedAuth;
    }

    public String getCooperateFlag() {
        return this.cooperateFlag;
    }

    public void setCooperateFlag(String cooperateFlag) {
        this.cooperateFlag = cooperateFlag;
    }

    public String getRequestSerialNo() {
        return this.requestSerialNo;
    }

    public void setRequestSerialNo(String requestSerialNo) {
        this.requestSerialNo = requestSerialNo;
    }

    public String getPurchaserEmail() {
        return this.purchaserEmail;
    }

    public void setPurchaserEmail(String purchaserEmail) {
        this.purchaserEmail = purchaserEmail;
    }

    public String getLogisticsStatus() {
        return this.logisticsStatus;
    }

    public void setLogisticsStatus(String logisticsStatus) {
        this.logisticsStatus = logisticsStatus;
    }

    public String getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    public String getCreateUserId() {
        return this.createUserId;
    }

    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    public String getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    public String getUpdateUserId() {
        return this.updateUserId;
    }

    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId;
    }

    public String getSpecialExt1() {
        return this.specialExt1;
    }

    public void setSpecialExt1(String specialExt1) {
        this.specialExt1 = specialExt1;
    }

    public String getSpecialExt2() {
        return this.specialExt2;
    }

    public void setSpecialExt2(String specialExt2) {
        this.specialExt2 = specialExt2;
    }

    public String getExt1() {
        return this.ext1;
    }

    public void setExt1(String ext1) {
        this.ext1 = ext1;
    }

    public String getExt2() {
        return this.ext2;
    }

    public void setExt2(String ext2) {
        this.ext2 = ext2;
    }

    public String getExt3() {
        return this.ext3;
    }

    public void setExt3(String ext3) {
        this.ext3 = ext3;
    }

    public String getExt4() {
        return this.ext4;
    }

    public void setExt4(String ext4) {
        this.ext4 = ext4;
    }

    public String getExt5() {
        return this.ext5;
    }

    public void setExt5(String ext5) {
        this.ext5 = ext5;
    }

    public String getExt6() {
        return this.ext6;
    }

    public void setExt6(String ext6) {
        this.ext6 = ext6;
    }

    public String getExt7() {
        return this.ext7;
    }

    public void setExt7(String ext7) {
        this.ext7 = ext7;
    }

    public String getExt8() {
        return this.ext8;
    }

    public void setExt8(String ext8) {
        this.ext8 = ext8;
    }

    public String getExt9() {
        return this.ext9;
    }

    public void setExt9(String ext9) {
        this.ext9 = ext9;
    }

    public String getExt10() {
        return this.ext10;
    }

    public void setExt10(String ext10) {
        this.ext10 = ext10;
    }

    public String getUploadWay() {
        return this.uploadWay;
    }

    public void setUploadWay(String uploadWay) {
        this.uploadWay = uploadWay;
    }

    public String getCashierName() {
        return this.cashierName;
    }

    public void setCashierName(String cashierName) {
        this.cashierName = cashierName;
    }

    public String getCheckerName() {
        return this.checkerName;
    }

    public void setCheckerName(String checkerName) {
        this.checkerName = checkerName;
    }

    public String getInvoicerName() {
        return this.invoicerName;
    }

    public void setInvoicerName(String invoicerName) {
        this.invoicerName = invoicerName;
    }

    public String getLockFlag() {
        return this.lockFlag;
    }

    public void setLockFlag(String lockFlag) {
        this.lockFlag = lockFlag;
    }

    public String getTaxRate() {
        return this.taxRate;
    }

    public void setTaxRate(String taxRate) {
        this.taxRate = taxRate;
    }

    public String getUseingStatus() {
        return this.useingStatus;
    }

    public void setUseingStatus(String useingStatus) {
        this.useingStatus = useingStatus;
    }

    public BigDecimal getPurAlreadyAmountWithoutTax() {
        return this.purAlreadyAmountWithoutTax;
    }

    public void setPurAlreadyAmountWithoutTax(BigDecimal purAlreadyAmountWithoutTax) {
        this.purAlreadyAmountWithoutTax = purAlreadyAmountWithoutTax;
    }

    public BigDecimal getPurAlreadyTaxAmount() {
        return this.purAlreadyTaxAmount;
    }

    public void setPurAlreadyTaxAmount(BigDecimal purAlreadyTaxAmount) {
        this.purAlreadyTaxAmount = purAlreadyTaxAmount;
    }

    public BigDecimal getPurAlreadyAmountWithTax() {
        return this.purAlreadyAmountWithTax;
    }

    public void setPurAlreadyAmountWithTax(BigDecimal purAlreadyAmountWithTax) {
        this.purAlreadyAmountWithTax = purAlreadyAmountWithTax;
    }

    public String getPrintContentFlag() {
        return this.printContentFlag;
    }

    public void setPrintContentFlag(String printContentFlag) {
        this.printContentFlag = printContentFlag;
    }

    public Integer getSellerInvoicePersonInfoId() {
        return this.sellerInvoicePersonInfoId;
    }

    public void setSellerInvoicePersonInfoId(Integer sellerInvoicePersonInfoId) {
        this.sellerInvoicePersonInfoId = sellerInvoicePersonInfoId;
    }

    public String getPurMachStatus() {
        return this.purMachStatus;
    }

    public void setPurMachStatus(String purMachStatus) {
        this.purMachStatus = purMachStatus;
    }

    public String getReciveUser() {
        return this.reciveUser;
    }

    public void setReciveUser(String reciveUser) {
        this.reciveUser = reciveUser;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TSettlementObj other = (TSettlementObj) obj;
        if (settlementId == null) {
            if (other.settlementId != null)
                return false;
        }
        else if (!settlementId.equals(other.settlementId))
            return false;
        if (settlementNo == null) {
            if (other.settlementNo != null)
                return false;
        }
        else if (!settlementNo.equals(other.settlementNo))
            return false;
        if (ruleId == null) {
            if (other.ruleId != null)
                return false;
        }
        else if (!ruleId.equals(other.ruleId))
            return false;
        if (settlementPeriod == null) {
            if (other.settlementPeriod != null)
                return false;
        }
        else if (!settlementPeriod.equals(other.settlementPeriod))
            return false;
        if (businessBillType == null) {
            if (other.businessBillType != null)
                return false;
        }
        else if (!businessBillType.equals(other.businessBillType))
            return false;
        if (invoiceType == null) {
            if (other.invoiceType != null)
                return false;
        }
        else if (!invoiceType.equals(other.invoiceType))
            return false;
        if (accordingRule == null) {
            if (other.accordingRule != null)
                return false;
        }
        else if (!accordingRule.equals(other.accordingRule))
            return false;
        if (predictInvoiceDate == null) {
            if (other.predictInvoiceDate != null)
                return false;
        }
        else if (!predictInvoiceDate.equals(other.predictInvoiceDate))
            return false;
        if (sellerTenantCode == null) {
            if (other.sellerTenantCode != null)
                return false;
        }
        else if (!sellerTenantCode.equals(other.sellerTenantCode))
            return false;
        if (sellerNoAr == null) {
            if (other.sellerNoAr != null)
                return false;
        }
        else if (!sellerNoAr.equals(other.sellerNoAr))
            return false;
        if (sellerNo == null) {
            if (other.sellerNo != null)
                return false;
        }
        else if (!sellerNo.equals(other.sellerNo))
            return false;
        if (sellerCode == null) {
            if (other.sellerCode != null)
                return false;
        }
        else if (!sellerCode.equals(other.sellerCode))
            return false;
        if (sellerTaxNo == null) {
            if (other.sellerTaxNo != null)
                return false;
        }
        else if (!sellerTaxNo.equals(other.sellerTaxNo))
            return false;
        if (sellerName == null) {
            if (other.sellerName != null)
                return false;
        }
        else if (!sellerName.equals(other.sellerName))
            return false;
        if (sellerAddress == null) {
            if (other.sellerAddress != null)
                return false;
        }
        else if (!sellerAddress.equals(other.sellerAddress))
            return false;
        if (sellerTel == null) {
            if (other.sellerTel != null)
                return false;
        }
        else if (!sellerTel.equals(other.sellerTel))
            return false;
        if (sellerBankName == null) {
            if (other.sellerBankName != null)
                return false;
        }
        else if (!sellerBankName.equals(other.sellerBankName))
            return false;
        if (sellerBankAccount == null) {
            if (other.sellerBankAccount != null)
                return false;
        }
        else if (!sellerBankAccount.equals(other.sellerBankAccount))
            return false;
        if (purchaserTenantCode == null) {
            if (other.purchaserTenantCode != null)
                return false;
        }
        else if (!purchaserTenantCode.equals(other.purchaserTenantCode))
            return false;
        if (purchaserNo == null) {
            if (other.purchaserNo != null)
                return false;
        }
        else if (!purchaserNo.equals(other.purchaserNo))
            return false;
        if (purchaserNoAr == null) {
            if (other.purchaserNoAr != null)
                return false;
        }
        else if (!purchaserNoAr.equals(other.purchaserNoAr))
            return false;
        if (purchaserCode == null) {
            if (other.purchaserCode != null)
                return false;
        }
        else if (!purchaserCode.equals(other.purchaserCode))
            return false;
        if (purchaserTaxNo == null) {
            if (other.purchaserTaxNo != null)
                return false;
        }
        else if (!purchaserTaxNo.equals(other.purchaserTaxNo))
            return false;
        if (purchaserName == null) {
            if (other.purchaserName != null)
                return false;
        }
        else if (!purchaserName.equals(other.purchaserName))
            return false;
        if (purchaserAddress == null) {
            if (other.purchaserAddress != null)
                return false;
        }
        else if (!purchaserAddress.equals(other.purchaserAddress))
            return false;
        if (purchaserTel == null) {
            if (other.purchaserTel != null)
                return false;
        }
        else if (!purchaserTel.equals(other.purchaserTel))
            return false;
        if (purchaserBankName == null) {
            if (other.purchaserBankName != null)
                return false;
        }
        else if (!purchaserBankName.equals(other.purchaserBankName))
            return false;
        if (purchaserBankAccount == null) {
            if (other.purchaserBankAccount != null)
                return false;
        }
        else if (!purchaserBankAccount.equals(other.purchaserBankAccount))
            return false;
        if (purchaserInvoiceInfoId == null) {
            if (other.purchaserInvoiceInfoId != null)
                return false;
        }
        else if (!purchaserInvoiceInfoId.equals(other.purchaserInvoiceInfoId))
            return false;
        if (sellerInvoiceInfoId == null) {
            if (other.sellerInvoiceInfoId != null)
                return false;
        }
        else if (!sellerInvoiceInfoId.equals(other.sellerInvoiceInfoId))
            return false;
        if (perinvoiceAmountLimit == null) {
            if (other.perinvoiceAmountLimit != null)
                return false;
        }
        else if (!perinvoiceAmountLimit.equals(other.perinvoiceAmountLimit))
            return false;
        if (otherPlatAccount == null) {
            if (other.otherPlatAccount != null)
                return false;
        }
        else if (!otherPlatAccount.equals(other.otherPlatAccount))
            return false;
        if (customBillType == null) {
            if (other.customBillType != null)
                return false;
        }
        else if (!customBillType.equals(other.customBillType))
            return false;
        if (amountWithoutTax == null) {
            if (other.amountWithoutTax != null)
                return false;
        }
        else if (!amountWithoutTax.equals(other.amountWithoutTax))
            return false;
        if (taxAmount == null) {
            if (other.taxAmount != null)
                return false;
        }
        else if (!taxAmount.equals(other.taxAmount))
            return false;
        if (amountWithTax == null) {
            if (other.amountWithTax != null)
                return false;
        }
        else if (!amountWithTax.equals(other.amountWithTax))
            return false;
        if (canMakeInvoiceAmountWithTax == null) {
            if (other.canMakeInvoiceAmountWithTax != null)
                return false;
        }
        else if (!canMakeInvoiceAmountWithTax.equals(other.canMakeInvoiceAmountWithTax))
            return false;
        if (alreadyInvoiceAmountWithTax == null) {
            if (other.alreadyInvoiceAmountWithTax != null)
                return false;
        }
        else if (!alreadyInvoiceAmountWithTax.equals(other.alreadyInvoiceAmountWithTax))
            return false;
        if (alreadyAuthAmountWithTax == null) {
            if (other.alreadyAuthAmountWithTax != null)
                return false;
        }
        else if (!alreadyAuthAmountWithTax.equals(other.alreadyAuthAmountWithTax))
            return false;
        if (canMakeInvoiceAmountWithoutTax == null) {
            if (other.canMakeInvoiceAmountWithoutTax != null)
                return false;
        }
        else if (!canMakeInvoiceAmountWithoutTax.equals(other.canMakeInvoiceAmountWithoutTax))
            return false;
        if (alreadyInvoiceAmountWithoutTax == null) {
            if (other.alreadyInvoiceAmountWithoutTax != null)
                return false;
        }
        else if (!alreadyInvoiceAmountWithoutTax.equals(other.alreadyInvoiceAmountWithoutTax))
            return false;
        if (alreadyAuthAmountWithoutTax == null) {
            if (other.alreadyAuthAmountWithoutTax != null)
                return false;
        }
        else if (!alreadyAuthAmountWithoutTax.equals(other.alreadyAuthAmountWithoutTax))
            return false;
        if (canMakeInvoiceTaxAmount == null) {
            if (other.canMakeInvoiceTaxAmount != null)
                return false;
        }
        else if (!canMakeInvoiceTaxAmount.equals(other.canMakeInvoiceTaxAmount))
            return false;
        if (alreadyInvoiceTaxAmount == null) {
            if (other.alreadyInvoiceTaxAmount != null)
                return false;
        }
        else if (!alreadyInvoiceTaxAmount.equals(other.alreadyInvoiceTaxAmount))
            return false;
        if (alreadyAuthTaxAmount == null) {
            if (other.alreadyAuthTaxAmount != null)
                return false;
        }
        else if (!alreadyAuthTaxAmount.equals(other.alreadyAuthTaxAmount))
            return false;
        if (alreadyPayTaxAmount == null) {
            if (other.alreadyPayTaxAmount != null)
                return false;
        }
        else if (!alreadyPayTaxAmount.equals(other.alreadyPayTaxAmount))
            return false;
        if (alreadyPayAmountWithoutTax == null) {
            if (other.alreadyPayAmountWithoutTax != null)
                return false;
        }
        else if (!alreadyPayAmountWithoutTax.equals(other.alreadyPayAmountWithoutTax))
            return false;
        if (alreadyPayAmountWihtTax == null) {
            if (other.alreadyPayAmountWihtTax != null)
                return false;
        }
        else if (!alreadyPayAmountWihtTax.equals(other.alreadyPayAmountWihtTax))
            return false;
        if (alreadyDeposeAmountWithTax == null) {
            if (other.alreadyDeposeAmountWithTax != null)
                return false;
        }
        else if (!alreadyDeposeAmountWithTax.equals(other.alreadyDeposeAmountWithTax))
            return false;
        if (alreadyRedAmountWithTax == null) {
            if (other.alreadyRedAmountWithTax != null)
                return false;
        }
        else if (!alreadyRedAmountWithTax.equals(other.alreadyRedAmountWithTax))
            return false;
        if (discountWithoutTax == null) {
            if (other.discountWithoutTax != null)
                return false;
        }
        else if (!discountWithoutTax.equals(other.discountWithoutTax))
            return false;
        if (discountTax == null) {
            if (other.discountTax != null)
                return false;
        }
        else if (!discountTax.equals(other.discountTax))
            return false;
        if (discountWithTax == null) {
            if (other.discountWithTax != null)
                return false;
        }
        else if (!discountWithTax.equals(other.discountWithTax))
            return false;
        if (remark == null) {
            if (other.remark != null)
                return false;
        }
        else if (!remark.equals(other.remark))
            return false;
        if (appendRemark == null) {
            if (other.appendRemark != null)
                return false;
        }
        else if (!appendRemark.equals(other.appendRemark))
            return false;
        if (preInvoiceNums == null) {
            if (other.preInvoiceNums != null)
                return false;
        }
        else if (!preInvoiceNums.equals(other.preInvoiceNums))
            return false;
        if (canMakeInvoiceNums == null) {
            if (other.canMakeInvoiceNums != null)
                return false;
        }
        else if (!canMakeInvoiceNums.equals(other.canMakeInvoiceNums))
            return false;
        if (invoiceNums == null) {
            if (other.invoiceNums != null)
                return false;
        }
        else if (!invoiceNums.equals(other.invoiceNums))
            return false;
        if (receiveConfirmFlag == null) {
            if (other.receiveConfirmFlag != null)
                return false;
        }
        else if (!receiveConfirmFlag.equals(other.receiveConfirmFlag))
            return false;
        if (uploadConfirmFlag == null) {
            if (other.uploadConfirmFlag != null)
                return false;
        }
        else if (!uploadConfirmFlag.equals(other.uploadConfirmFlag))
            return false;
        if (status == null) {
            if (other.status != null)
                return false;
        }
        else if (!status.equals(other.status))
            return false;
        if (originInvoiceNo == null) {
            if (other.originInvoiceNo != null)
                return false;
        }
        else if (!originInvoiceNo.equals(other.originInvoiceNo))
            return false;
        if (originInvoiceCode == null) {
            if (other.originInvoiceCode != null)
                return false;
        }
        else if (!originInvoiceCode.equals(other.originInvoiceCode))
            return false;
        if (redNotificationNo == null) {
            if (other.redNotificationNo != null)
                return false;
        }
        else if (!redNotificationNo.equals(other.redNotificationNo))
            return false;
        if (orderNo == null) {
            if (other.orderNo != null)
                return false;
        }
        else if (!orderNo.equals(other.orderNo))
            return false;
        if (contractNo == null) {
            if (other.contractNo != null)
                return false;
        }
        else if (!contractNo.equals(other.contractNo))
            return false;
        if (systemOrig == null) {
            if (other.systemOrig != null)
                return false;
        }
        else if (!systemOrig.equals(other.systemOrig))
            return false;
        if (salesBillNo == null) {
            if (other.salesBillNo != null)
                return false;
        }
        else if (!salesBillNo.equals(other.salesBillNo))
            return false;
        if (isNeedAuth == null) {
            if (other.isNeedAuth != null)
                return false;
        }
        else if (!isNeedAuth.equals(other.isNeedAuth))
            return false;
        if (cooperateFlag == null) {
            if (other.cooperateFlag != null)
                return false;
        }
        else if (!cooperateFlag.equals(other.cooperateFlag))
            return false;
        if (requestSerialNo == null) {
            if (other.requestSerialNo != null)
                return false;
        }
        else if (!requestSerialNo.equals(other.requestSerialNo))
            return false;
        if (purchaserEmail == null) {
            if (other.purchaserEmail != null)
                return false;
        }
        else if (!purchaserEmail.equals(other.purchaserEmail))
            return false;
        if (logisticsStatus == null) {
            if (other.logisticsStatus != null)
                return false;
        }
        else if (!logisticsStatus.equals(other.logisticsStatus))
            return false;
        if (createTime == null) {
            if (other.createTime != null)
                return false;
        }
        else if (!createTime.equals(other.createTime))
            return false;
        if (createUserId == null) {
            if (other.createUserId != null)
                return false;
        }
        else if (!createUserId.equals(other.createUserId))
            return false;
        if (updateTime == null) {
            if (other.updateTime != null)
                return false;
        }
        else if (!updateTime.equals(other.updateTime))
            return false;
        if (updateUserId == null) {
            if (other.updateUserId != null)
                return false;
        }
        else if (!updateUserId.equals(other.updateUserId))
            return false;
        if (specialExt1 == null) {
            if (other.specialExt1 != null)
                return false;
        }
        else if (!specialExt1.equals(other.specialExt1))
            return false;
        if (specialExt2 == null) {
            if (other.specialExt2 != null)
                return false;
        }
        else if (!specialExt2.equals(other.specialExt2))
            return false;
        if (ext1 == null) {
            if (other.ext1 != null)
                return false;
        }
        else if (!ext1.equals(other.ext1))
            return false;
        if (ext2 == null) {
            if (other.ext2 != null)
                return false;
        }
        else if (!ext2.equals(other.ext2))
            return false;
        if (ext3 == null) {
            if (other.ext3 != null)
                return false;
        }
        else if (!ext3.equals(other.ext3))
            return false;
        if (ext4 == null) {
            if (other.ext4 != null)
                return false;
        }
        else if (!ext4.equals(other.ext4))
            return false;
        if (ext5 == null) {
            if (other.ext5 != null)
                return false;
        }
        else if (!ext5.equals(other.ext5))
            return false;
        if (ext6 == null) {
            if (other.ext6 != null)
                return false;
        }
        else if (!ext6.equals(other.ext6))
            return false;
        if (ext7 == null) {
            if (other.ext7 != null)
                return false;
        }
        else if (!ext7.equals(other.ext7))
            return false;
        if (ext8 == null) {
            if (other.ext8 != null)
                return false;
        }
        else if (!ext8.equals(other.ext8))
            return false;
        if (ext9 == null) {
            if (other.ext9 != null)
                return false;
        }
        else if (!ext9.equals(other.ext9))
            return false;
        if (ext10 == null) {
            if (other.ext10 != null)
                return false;
        }
        else if (!ext10.equals(other.ext10))
            return false;
        if (uploadWay == null) {
            if (other.uploadWay != null)
                return false;
        }
        else if (!uploadWay.equals(other.uploadWay))
            return false;
        if (cashierName == null) {
            if (other.cashierName != null)
                return false;
        }
        else if (!cashierName.equals(other.cashierName))
            return false;
        if (checkerName == null) {
            if (other.checkerName != null)
                return false;
        }
        else if (!checkerName.equals(other.checkerName))
            return false;
        if (invoicerName == null) {
            if (other.invoicerName != null)
                return false;
        }
        else if (!invoicerName.equals(other.invoicerName))
            return false;
        if (lockFlag == null) {
            if (other.lockFlag != null)
                return false;
        }
        else if (!lockFlag.equals(other.lockFlag))
            return false;
        if (taxRate == null) {
            if (other.taxRate != null)
                return false;
        }
        else if (!taxRate.equals(other.taxRate))
            return false;
        if (useingStatus == null) {
            if (other.useingStatus != null)
                return false;
        }
        else if (!useingStatus.equals(other.useingStatus))
            return false;
        if (purAlreadyAmountWithoutTax == null) {
            if (other.purAlreadyAmountWithoutTax != null)
                return false;
        }
        else if (!purAlreadyAmountWithoutTax.equals(other.purAlreadyAmountWithoutTax))
            return false;
        if (purAlreadyTaxAmount == null) {
            if (other.purAlreadyTaxAmount != null)
                return false;
        }
        else if (!purAlreadyTaxAmount.equals(other.purAlreadyTaxAmount))
            return false;
        if (purAlreadyAmountWithTax == null) {
            if (other.purAlreadyAmountWithTax != null)
                return false;
        }
        else if (!purAlreadyAmountWithTax.equals(other.purAlreadyAmountWithTax))
            return false;
        if (printContentFlag == null) {
            if (other.printContentFlag != null)
                return false;
        }
        else if (!printContentFlag.equals(other.printContentFlag))
            return false;
        if (sellerInvoicePersonInfoId == null) {
            if (other.sellerInvoicePersonInfoId != null)
                return false;
        }
        else if (!sellerInvoicePersonInfoId.equals(other.sellerInvoicePersonInfoId))
            return false;
        if (purMachStatus == null) {
            if (other.purMachStatus != null)
                return false;
        }
        else if (!purMachStatus.equals(other.purMachStatus))
            return false;
        if (reciveUser == null) {
            if (other.reciveUser != null)
                return false;
        }
        else if (!reciveUser.equals(other.reciveUser))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((settlementId == null) ? 0 : settlementId.hashCode());
        result = prime * result + ((settlementNo == null) ? 0 : settlementNo.hashCode());
        result = prime * result + ((ruleId == null) ? 0 : ruleId.hashCode());
        result = prime * result + ((settlementPeriod == null) ? 0 : settlementPeriod.hashCode());
        result = prime * result + ((businessBillType == null) ? 0 : businessBillType.hashCode());
        result = prime * result + ((invoiceType == null) ? 0 : invoiceType.hashCode());
        result = prime * result + ((accordingRule == null) ? 0 : accordingRule.hashCode());
        result = prime * result + ((predictInvoiceDate == null) ? 0 : predictInvoiceDate.hashCode());
        result = prime * result + ((sellerTenantCode == null) ? 0 : sellerTenantCode.hashCode());
        result = prime * result + ((sellerNoAr == null) ? 0 : sellerNoAr.hashCode());
        result = prime * result + ((sellerNo == null) ? 0 : sellerNo.hashCode());
        result = prime * result + ((sellerCode == null) ? 0 : sellerCode.hashCode());
        result = prime * result + ((sellerTaxNo == null) ? 0 : sellerTaxNo.hashCode());
        result = prime * result + ((sellerName == null) ? 0 : sellerName.hashCode());
        result = prime * result + ((sellerAddress == null) ? 0 : sellerAddress.hashCode());
        result = prime * result + ((sellerTel == null) ? 0 : sellerTel.hashCode());
        result = prime * result + ((sellerBankName == null) ? 0 : sellerBankName.hashCode());
        result = prime * result + ((sellerBankAccount == null) ? 0 : sellerBankAccount.hashCode());
        result = prime * result + ((purchaserTenantCode == null) ? 0 : purchaserTenantCode.hashCode());
        result = prime * result + ((purchaserNo == null) ? 0 : purchaserNo.hashCode());
        result = prime * result + ((purchaserNoAr == null) ? 0 : purchaserNoAr.hashCode());
        result = prime * result + ((purchaserCode == null) ? 0 : purchaserCode.hashCode());
        result = prime * result + ((purchaserTaxNo == null) ? 0 : purchaserTaxNo.hashCode());
        result = prime * result + ((purchaserName == null) ? 0 : purchaserName.hashCode());
        result = prime * result + ((purchaserAddress == null) ? 0 : purchaserAddress.hashCode());
        result = prime * result + ((purchaserTel == null) ? 0 : purchaserTel.hashCode());
        result = prime * result + ((purchaserBankName == null) ? 0 : purchaserBankName.hashCode());
        result = prime * result + ((purchaserBankAccount == null) ? 0 : purchaserBankAccount.hashCode());
        result = prime * result + ((purchaserInvoiceInfoId == null) ? 0 : purchaserInvoiceInfoId.hashCode());
        result = prime * result + ((sellerInvoiceInfoId == null) ? 0 : sellerInvoiceInfoId.hashCode());
        result = prime * result + ((perinvoiceAmountLimit == null) ? 0 : perinvoiceAmountLimit.hashCode());
        result = prime * result + ((otherPlatAccount == null) ? 0 : otherPlatAccount.hashCode());
        result = prime * result + ((customBillType == null) ? 0 : customBillType.hashCode());
        result = prime * result + ((amountWithoutTax == null) ? 0 : amountWithoutTax.hashCode());
        result = prime * result + ((taxAmount == null) ? 0 : taxAmount.hashCode());
        result = prime * result + ((amountWithTax == null) ? 0 : amountWithTax.hashCode());
        result = prime * result + ((canMakeInvoiceAmountWithTax == null) ? 0 : canMakeInvoiceAmountWithTax.hashCode());
        result = prime * result + ((alreadyInvoiceAmountWithTax == null) ? 0 : alreadyInvoiceAmountWithTax.hashCode());
        result = prime * result + ((alreadyAuthAmountWithTax == null) ? 0 : alreadyAuthAmountWithTax.hashCode());
        result = prime * result + ((canMakeInvoiceAmountWithoutTax == null) ? 0 : canMakeInvoiceAmountWithoutTax.hashCode());
        result = prime * result + ((alreadyInvoiceAmountWithoutTax == null) ? 0 : alreadyInvoiceAmountWithoutTax.hashCode());
        result = prime * result + ((alreadyAuthAmountWithoutTax == null) ? 0 : alreadyAuthAmountWithoutTax.hashCode());
        result = prime * result + ((canMakeInvoiceTaxAmount == null) ? 0 : canMakeInvoiceTaxAmount.hashCode());
        result = prime * result + ((alreadyInvoiceTaxAmount == null) ? 0 : alreadyInvoiceTaxAmount.hashCode());
        result = prime * result + ((alreadyAuthTaxAmount == null) ? 0 : alreadyAuthTaxAmount.hashCode());
        result = prime * result + ((alreadyPayTaxAmount == null) ? 0 : alreadyPayTaxAmount.hashCode());
        result = prime * result + ((alreadyPayAmountWithoutTax == null) ? 0 : alreadyPayAmountWithoutTax.hashCode());
        result = prime * result + ((alreadyPayAmountWihtTax == null) ? 0 : alreadyPayAmountWihtTax.hashCode());
        result = prime * result + ((alreadyDeposeAmountWithTax == null) ? 0 : alreadyDeposeAmountWithTax.hashCode());
        result = prime * result + ((alreadyRedAmountWithTax == null) ? 0 : alreadyRedAmountWithTax.hashCode());
        result = prime * result + ((discountWithoutTax == null) ? 0 : discountWithoutTax.hashCode());
        result = prime * result + ((discountTax == null) ? 0 : discountTax.hashCode());
        result = prime * result + ((discountWithTax == null) ? 0 : discountWithTax.hashCode());
        result = prime * result + ((remark == null) ? 0 : remark.hashCode());
        result = prime * result + ((appendRemark == null) ? 0 : appendRemark.hashCode());
        result = prime * result + ((preInvoiceNums == null) ? 0 : preInvoiceNums.hashCode());
        result = prime * result + ((canMakeInvoiceNums == null) ? 0 : canMakeInvoiceNums.hashCode());
        result = prime * result + ((invoiceNums == null) ? 0 : invoiceNums.hashCode());
        result = prime * result + ((receiveConfirmFlag == null) ? 0 : receiveConfirmFlag.hashCode());
        result = prime * result + ((uploadConfirmFlag == null) ? 0 : uploadConfirmFlag.hashCode());
        result = prime * result + ((status == null) ? 0 : status.hashCode());
        result = prime * result + ((originInvoiceNo == null) ? 0 : originInvoiceNo.hashCode());
        result = prime * result + ((originInvoiceCode == null) ? 0 : originInvoiceCode.hashCode());
        result = prime * result + ((redNotificationNo == null) ? 0 : redNotificationNo.hashCode());
        result = prime * result + ((orderNo == null) ? 0 : orderNo.hashCode());
        result = prime * result + ((contractNo == null) ? 0 : contractNo.hashCode());
        result = prime * result + ((systemOrig == null) ? 0 : systemOrig.hashCode());
        result = prime * result + ((salesBillNo == null) ? 0 : salesBillNo.hashCode());
        result = prime * result + ((isNeedAuth == null) ? 0 : isNeedAuth.hashCode());
        result = prime * result + ((cooperateFlag == null) ? 0 : cooperateFlag.hashCode());
        result = prime * result + ((requestSerialNo == null) ? 0 : requestSerialNo.hashCode());
        result = prime * result + ((purchaserEmail == null) ? 0 : purchaserEmail.hashCode());
        result = prime * result + ((logisticsStatus == null) ? 0 : logisticsStatus.hashCode());
        result = prime * result + ((createTime == null) ? 0 : createTime.hashCode());
        result = prime * result + ((createUserId == null) ? 0 : createUserId.hashCode());
        result = prime * result + ((updateTime == null) ? 0 : updateTime.hashCode());
        result = prime * result + ((updateUserId == null) ? 0 : updateUserId.hashCode());
        result = prime * result + ((specialExt1 == null) ? 0 : specialExt1.hashCode());
        result = prime * result + ((specialExt2 == null) ? 0 : specialExt2.hashCode());
        result = prime * result + ((ext1 == null) ? 0 : ext1.hashCode());
        result = prime * result + ((ext2 == null) ? 0 : ext2.hashCode());
        result = prime * result + ((ext3 == null) ? 0 : ext3.hashCode());
        result = prime * result + ((ext4 == null) ? 0 : ext4.hashCode());
        result = prime * result + ((ext5 == null) ? 0 : ext5.hashCode());
        result = prime * result + ((ext6 == null) ? 0 : ext6.hashCode());
        result = prime * result + ((ext7 == null) ? 0 : ext7.hashCode());
        result = prime * result + ((ext8 == null) ? 0 : ext8.hashCode());
        result = prime * result + ((ext9 == null) ? 0 : ext9.hashCode());
        result = prime * result + ((ext10 == null) ? 0 : ext10.hashCode());
        result = prime * result + ((uploadWay == null) ? 0 : uploadWay.hashCode());
        result = prime * result + ((cashierName == null) ? 0 : cashierName.hashCode());
        result = prime * result + ((checkerName == null) ? 0 : checkerName.hashCode());
        result = prime * result + ((invoicerName == null) ? 0 : invoicerName.hashCode());
        result = prime * result + ((lockFlag == null) ? 0 : lockFlag.hashCode());
        result = prime * result + ((taxRate == null) ? 0 : taxRate.hashCode());
        result = prime * result + ((useingStatus == null) ? 0 : useingStatus.hashCode());
        result = prime * result + ((purAlreadyAmountWithoutTax == null) ? 0 : purAlreadyAmountWithoutTax.hashCode());
        result = prime * result + ((purAlreadyTaxAmount == null) ? 0 : purAlreadyTaxAmount.hashCode());
        result = prime * result + ((purAlreadyAmountWithTax == null) ? 0 : purAlreadyAmountWithTax.hashCode());
        result = prime * result + ((printContentFlag == null) ? 0 : printContentFlag.hashCode());
        result = prime * result + ((sellerInvoicePersonInfoId == null) ? 0 : sellerInvoicePersonInfoId.hashCode());
        result = prime * result + ((purMachStatus == null) ? 0 : purMachStatus.hashCode());
        result = prime * result + ((reciveUser == null) ? 0 : reciveUser.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TSettlementObj (");

        sb.append(settlementId);
        sb.append(", ").append(settlementNo);
        sb.append(", ").append(ruleId);
        sb.append(", ").append(settlementPeriod);
        sb.append(", ").append(businessBillType);
        sb.append(", ").append(invoiceType);
        sb.append(", ").append(accordingRule);
        sb.append(", ").append(predictInvoiceDate);
        sb.append(", ").append(sellerTenantCode);
        sb.append(", ").append(sellerNoAr);
        sb.append(", ").append(sellerNo);
        sb.append(", ").append(sellerCode);
        sb.append(", ").append(sellerTaxNo);
        sb.append(", ").append(sellerName);
        sb.append(", ").append(sellerAddress);
        sb.append(", ").append(sellerTel);
        sb.append(", ").append(sellerBankName);
        sb.append(", ").append(sellerBankAccount);
        sb.append(", ").append(purchaserTenantCode);
        sb.append(", ").append(purchaserNo);
        sb.append(", ").append(purchaserNoAr);
        sb.append(", ").append(purchaserCode);
        sb.append(", ").append(purchaserTaxNo);
        sb.append(", ").append(purchaserName);
        sb.append(", ").append(purchaserAddress);
        sb.append(", ").append(purchaserTel);
        sb.append(", ").append(purchaserBankName);
        sb.append(", ").append(purchaserBankAccount);
        sb.append(", ").append(purchaserInvoiceInfoId);
        sb.append(", ").append(sellerInvoiceInfoId);
        sb.append(", ").append(perinvoiceAmountLimit);
        sb.append(", ").append(otherPlatAccount);
        sb.append(", ").append(customBillType);
        sb.append(", ").append(amountWithoutTax);
        sb.append(", ").append(taxAmount);
        sb.append(", ").append(amountWithTax);
        sb.append(", ").append(canMakeInvoiceAmountWithTax);
        sb.append(", ").append(alreadyInvoiceAmountWithTax);
        sb.append(", ").append(alreadyAuthAmountWithTax);
        sb.append(", ").append(canMakeInvoiceAmountWithoutTax);
        sb.append(", ").append(alreadyInvoiceAmountWithoutTax);
        sb.append(", ").append(alreadyAuthAmountWithoutTax);
        sb.append(", ").append(canMakeInvoiceTaxAmount);
        sb.append(", ").append(alreadyInvoiceTaxAmount);
        sb.append(", ").append(alreadyAuthTaxAmount);
        sb.append(", ").append(alreadyPayTaxAmount);
        sb.append(", ").append(alreadyPayAmountWithoutTax);
        sb.append(", ").append(alreadyPayAmountWihtTax);
        sb.append(", ").append(alreadyDeposeAmountWithTax);
        sb.append(", ").append(alreadyRedAmountWithTax);
        sb.append(", ").append(discountWithoutTax);
        sb.append(", ").append(discountTax);
        sb.append(", ").append(discountWithTax);
        sb.append(", ").append(remark);
        sb.append(", ").append(appendRemark);
        sb.append(", ").append(preInvoiceNums);
        sb.append(", ").append(canMakeInvoiceNums);
        sb.append(", ").append(invoiceNums);
        sb.append(", ").append(receiveConfirmFlag);
        sb.append(", ").append(uploadConfirmFlag);
        sb.append(", ").append(status);
        sb.append(", ").append(originInvoiceNo);
        sb.append(", ").append(originInvoiceCode);
        sb.append(", ").append(redNotificationNo);
        sb.append(", ").append(orderNo);
        sb.append(", ").append(contractNo);
        sb.append(", ").append(systemOrig);
        sb.append(", ").append(salesBillNo);
        sb.append(", ").append(isNeedAuth);
        sb.append(", ").append(cooperateFlag);
        sb.append(", ").append(requestSerialNo);
        sb.append(", ").append(purchaserEmail);
        sb.append(", ").append(logisticsStatus);
        sb.append(", ").append(createTime);
        sb.append(", ").append(createUserId);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(updateUserId);
        sb.append(", ").append(specialExt1);
        sb.append(", ").append(specialExt2);
        sb.append(", ").append(ext1);
        sb.append(", ").append(ext2);
        sb.append(", ").append(ext3);
        sb.append(", ").append(ext4);
        sb.append(", ").append(ext5);
        sb.append(", ").append(ext6);
        sb.append(", ").append(ext7);
        sb.append(", ").append(ext8);
        sb.append(", ").append(ext9);
        sb.append(", ").append(ext10);
        sb.append(", ").append(uploadWay);
        sb.append(", ").append(cashierName);
        sb.append(", ").append(checkerName);
        sb.append(", ").append(invoicerName);
        sb.append(", ").append(lockFlag);
        sb.append(", ").append(taxRate);
        sb.append(", ").append(useingStatus);
        sb.append(", ").append(purAlreadyAmountWithoutTax);
        sb.append(", ").append(purAlreadyTaxAmount);
        sb.append(", ").append(purAlreadyAmountWithTax);
        sb.append(", ").append(printContentFlag);
        sb.append(", ").append(sellerInvoicePersonInfoId);
        sb.append(", ").append(purMachStatus);
        sb.append(", ").append(reciveUser);

        sb.append(")");
        return sb.toString();
    }
}
