/*
 * This file is generated by jOOQ.
*/
package com.chenqiguang.springboot.domain.jooq.tables;


import com.chenqiguang.springboot.domain.jooq.Chenqiguang;
import com.chenqiguang.springboot.domain.jooq.Keys;
import com.chenqiguang.springboot.domain.jooq.tables.records.TSettlementRecord;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * 结算单表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TSettlement extends TableImpl<TSettlementRecord> {

    private static final long serialVersionUID = 761637741;

    /**
     * The reference instance of <code>chenqiguang.t_settlement</code>
     */
    public static final TSettlement T_SETTLEMENT = new TSettlement();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TSettlementRecord> getRecordType() {
        return TSettlementRecord.class;
    }

    /**
     * The column <code>chenqiguang.t_settlement.SETTLEMENT_ID</code>. 结算单序号
UUID
     */
    public final TableField<TSettlementRecord, String> SETTLEMENT_ID = createField("SETTLEMENT_ID", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "结算单序号\nUUID");

    /**
     * The column <code>chenqiguang.t_settlement.SETTLEMENT_NO</code>. 结算单号(企业)
     */
    public final TableField<TSettlementRecord, String> SETTLEMENT_NO = createField("SETTLEMENT_NO", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "结算单号(企业)");

    /**
     * The column <code>chenqiguang.t_settlement.RULE_ID</code>. 开票规则
     */
    public final TableField<TSettlementRecord, Long> RULE_ID = createField("RULE_ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "开票规则");

    /**
     * The column <code>chenqiguang.t_settlement.SETTLEMENT_PERIOD</code>. 开票结算期间
     */
    public final TableField<TSettlementRecord, String> SETTLEMENT_PERIOD = createField("SETTLEMENT_PERIOD", org.jooq.impl.SQLDataType.VARCHAR.length(6).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "开票结算期间");

    /**
     * The column <code>chenqiguang.t_settlement.BUSINESS_BILL_TYPE</code>. 适用业务单据类型 
     */
    public final TableField<TSettlementRecord, String> BUSINESS_BILL_TYPE = createField("BUSINESS_BILL_TYPE", org.jooq.impl.SQLDataType.VARCHAR.length(2).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "适用业务单据类型 ");

    /**
     * The column <code>chenqiguang.t_settlement.INVOICE_TYPE</code>. 发票类型 
     */
    public final TableField<TSettlementRecord, String> INVOICE_TYPE = createField("INVOICE_TYPE", org.jooq.impl.SQLDataType.VARCHAR.length(2).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "发票类型 ");

    /**
     * The column <code>chenqiguang.t_settlement.ACCORDING_RULE</code>. 所关联发票是否全按规则开具  0-否 1-是
     */
    public final TableField<TSettlementRecord, String> ACCORDING_RULE = createField("ACCORDING_RULE", org.jooq.impl.SQLDataType.VARCHAR.length(1).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "所关联发票是否全按规则开具  0-否 1-是");

    /**
     * The column <code>chenqiguang.t_settlement.PREDICT_INVOICE_DATE</code>. 期望开票日期
     */
    public final TableField<TSettlementRecord, String> PREDICT_INVOICE_DATE = createField("PREDICT_INVOICE_DATE", org.jooq.impl.SQLDataType.VARCHAR.length(8).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "期望开票日期");

    /**
     * The column <code>chenqiguang.t_settlement.SELLER_TENANT_CODE</code>. 销方租户代码
     */
    public final TableField<TSettlementRecord, String> SELLER_TENANT_CODE = createField("SELLER_TENANT_CODE", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "销方租户代码");

    /**
     * The column <code>chenqiguang.t_settlement.SELLER_NO_AR</code>. 销方编号（AR导入）
     */
    public final TableField<TSettlementRecord, String> SELLER_NO_AR = createField("SELLER_NO_AR", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "销方编号（AR导入）");

    /**
     * The column <code>chenqiguang.t_settlement.SELLER_NO</code>. 销方编号（企业）
     */
    public final TableField<TSettlementRecord, String> SELLER_NO = createField("SELLER_NO", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "销方编号（企业）");

    /**
     * The column <code>chenqiguang.t_settlement.SELLER_CODE</code>. 销方代码(平台)
     */
    public final TableField<TSettlementRecord, String> SELLER_CODE = createField("SELLER_CODE", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "销方代码(平台)");

    /**
     * The column <code>chenqiguang.t_settlement.SELLER_TAX_NO</code>. 销方税号
     */
    public final TableField<TSettlementRecord, String> SELLER_TAX_NO = createField("SELLER_TAX_NO", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "销方税号");

    /**
     * The column <code>chenqiguang.t_settlement.SELLER_NAME</code>. 销方名称
     */
    public final TableField<TSettlementRecord, String> SELLER_NAME = createField("SELLER_NAME", org.jooq.impl.SQLDataType.VARCHAR.length(200).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "销方名称");

    /**
     * The column <code>chenqiguang.t_settlement.SELLER_ADDRESS</code>. 销方地址
     */
    public final TableField<TSettlementRecord, String> SELLER_ADDRESS = createField("SELLER_ADDRESS", org.jooq.impl.SQLDataType.VARCHAR.length(200).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "销方地址");

    /**
     * The column <code>chenqiguang.t_settlement.SELLER_TEL</code>. 销方电话
     */
    public final TableField<TSettlementRecord, String> SELLER_TEL = createField("SELLER_TEL", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "销方电话");

    /**
     * The column <code>chenqiguang.t_settlement.SELLER_BANK_NAME</code>. 销方银行名称
     */
    public final TableField<TSettlementRecord, String> SELLER_BANK_NAME = createField("SELLER_BANK_NAME", org.jooq.impl.SQLDataType.VARCHAR.length(200).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "销方银行名称");

    /**
     * The column <code>chenqiguang.t_settlement.SELLER_BANK_ACCOUNT</code>. 销方银行账号
     */
    public final TableField<TSettlementRecord, String> SELLER_BANK_ACCOUNT = createField("SELLER_BANK_ACCOUNT", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "销方银行账号");

    /**
     * The column <code>chenqiguang.t_settlement.PURCHASER_TENANT_CODE</code>. 购方分组代码
     */
    public final TableField<TSettlementRecord, String> PURCHASER_TENANT_CODE = createField("PURCHASER_TENANT_CODE", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "购方分组代码");

    /**
     * The column <code>chenqiguang.t_settlement.PURCHASER_NO</code>. 购方编号（企业）
     */
    public final TableField<TSettlementRecord, String> PURCHASER_NO = createField("PURCHASER_NO", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "购方编号（企业）");

    /**
     * The column <code>chenqiguang.t_settlement.PURCHASER_NO_AR</code>. 购方编号（AR导入）
     */
    public final TableField<TSettlementRecord, String> PURCHASER_NO_AR = createField("PURCHASER_NO_AR", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "购方编号（AR导入）");

    /**
     * The column <code>chenqiguang.t_settlement.PURCHASER_CODE</code>. 购方代码(平台)
     */
    public final TableField<TSettlementRecord, String> PURCHASER_CODE = createField("PURCHASER_CODE", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "购方代码(平台)");

    /**
     * The column <code>chenqiguang.t_settlement.PURCHASER_TAX_NO</code>. 购方税号
     */
    public final TableField<TSettlementRecord, String> PURCHASER_TAX_NO = createField("PURCHASER_TAX_NO", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "购方税号");

    /**
     * The column <code>chenqiguang.t_settlement.PURCHASER_NAME</code>. 购方名称
     */
    public final TableField<TSettlementRecord, String> PURCHASER_NAME = createField("PURCHASER_NAME", org.jooq.impl.SQLDataType.VARCHAR.length(200).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "购方名称");

    /**
     * The column <code>chenqiguang.t_settlement.PURCHASER_ADDRESS</code>. 购方地址
     */
    public final TableField<TSettlementRecord, String> PURCHASER_ADDRESS = createField("PURCHASER_ADDRESS", org.jooq.impl.SQLDataType.VARCHAR.length(200).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "购方地址");

    /**
     * The column <code>chenqiguang.t_settlement.PURCHASER_TEL</code>. 购方电话
     */
    public final TableField<TSettlementRecord, String> PURCHASER_TEL = createField("PURCHASER_TEL", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "购方电话");

    /**
     * The column <code>chenqiguang.t_settlement.PURCHASER_BANK_NAME</code>. 购方银行名称
     */
    public final TableField<TSettlementRecord, String> PURCHASER_BANK_NAME = createField("PURCHASER_BANK_NAME", org.jooq.impl.SQLDataType.VARCHAR.length(200).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "购方银行名称");

    /**
     * The column <code>chenqiguang.t_settlement.PURCHASER_BANK_ACCOUNT</code>. 购方银行账号
     */
    public final TableField<TSettlementRecord, String> PURCHASER_BANK_ACCOUNT = createField("PURCHASER_BANK_ACCOUNT", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "购方银行账号");

    /**
     * The column <code>chenqiguang.t_settlement.PURCHASER_INVOICE_INFO_ID</code>. 购方票面信息id
     */
    public final TableField<TSettlementRecord, Integer> PURCHASER_INVOICE_INFO_ID = createField("PURCHASER_INVOICE_INFO_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "购方票面信息id");

    /**
     * The column <code>chenqiguang.t_settlement.SELLER_INVOICE_INFO_ID</code>. 销方票面信息id
     */
    public final TableField<TSettlementRecord, Integer> SELLER_INVOICE_INFO_ID = createField("SELLER_INVOICE_INFO_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "销方票面信息id");

    /**
     * The column <code>chenqiguang.t_settlement.PERINVOICE_AMOUNT_LIMIT</code>. 单张发票不含税限额
     */
    public final TableField<TSettlementRecord, BigDecimal> PERINVOICE_AMOUNT_LIMIT = createField("PERINVOICE_AMOUNT_LIMIT", org.jooq.impl.SQLDataType.DECIMAL.precision(18, 2).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0.00", org.jooq.impl.SQLDataType.DECIMAL)), this, "单张发票不含税限额");

    /**
     * The column <code>chenqiguang.t_settlement.OTHER_PLAT_ACCOUNT</code>. 第三方平台账号
之前的ext4固化为这个字段
     */
    public final TableField<TSettlementRecord, String> OTHER_PLAT_ACCOUNT = createField("OTHER_PLAT_ACCOUNT", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "第三方平台账号\n之前的ext4固化为这个字段");

    /**
     * The column <code>chenqiguang.t_settlement.CUSTOM_BILL_TYPE</code>. 结算单类型明细
用于特定情况结算单再分类
     */
    public final TableField<TSettlementRecord, String> CUSTOM_BILL_TYPE = createField("CUSTOM_BILL_TYPE", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "结算单类型明细\n用于特定情况结算单再分类");

    /**
     * The column <code>chenqiguang.t_settlement.AMOUNT_WITHOUT_TAX</code>. 不含税金额
     */
    public final TableField<TSettlementRecord, BigDecimal> AMOUNT_WITHOUT_TAX = createField("AMOUNT_WITHOUT_TAX", org.jooq.impl.SQLDataType.DECIMAL.precision(18, 6).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0.000000", org.jooq.impl.SQLDataType.DECIMAL)), this, "不含税金额");

    /**
     * The column <code>chenqiguang.t_settlement.TAX_AMOUNT</code>. 税额
     */
    public final TableField<TSettlementRecord, BigDecimal> TAX_AMOUNT = createField("TAX_AMOUNT", org.jooq.impl.SQLDataType.DECIMAL.precision(18, 6).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0.000000", org.jooq.impl.SQLDataType.DECIMAL)), this, "税额");

    /**
     * The column <code>chenqiguang.t_settlement.AMOUNT_WITH_TAX</code>. 含税金额
     */
    public final TableField<TSettlementRecord, BigDecimal> AMOUNT_WITH_TAX = createField("AMOUNT_WITH_TAX", org.jooq.impl.SQLDataType.DECIMAL.precision(18, 6).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0.000000", org.jooq.impl.SQLDataType.DECIMAL)), this, "含税金额");

    /**
     * The column <code>chenqiguang.t_settlement.CAN_MAKE_INVOICE_AMOUNT_WITH_TAX</code>. 可开正式发票含税金额
新增字段=含税金额（amountWithTax）减去已开正式发票金额
     */
    public final TableField<TSettlementRecord, BigDecimal> CAN_MAKE_INVOICE_AMOUNT_WITH_TAX = createField("CAN_MAKE_INVOICE_AMOUNT_WITH_TAX", org.jooq.impl.SQLDataType.DECIMAL.precision(18, 6).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0.000000", org.jooq.impl.SQLDataType.DECIMAL)), this, "可开正式发票含税金额\n新增字段=含税金额（amountWithTax）减去已开正式发票金额");

    /**
     * The column <code>chenqiguang.t_settlement.ALREADY_INVOICE_AMOUNT_WITH_TAX</code>. 已开正式发票含税金额
     */
    public final TableField<TSettlementRecord, BigDecimal> ALREADY_INVOICE_AMOUNT_WITH_TAX = createField("ALREADY_INVOICE_AMOUNT_WITH_TAX", org.jooq.impl.SQLDataType.DECIMAL.precision(18, 6).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0.000000", org.jooq.impl.SQLDataType.DECIMAL)), this, "已开正式发票含税金额");

    /**
     * The column <code>chenqiguang.t_settlement.ALREADY_AUTH_AMOUNT_WITH_TAX</code>. 已认证含税金额
保留
     */
    public final TableField<TSettlementRecord, BigDecimal> ALREADY_AUTH_AMOUNT_WITH_TAX = createField("ALREADY_AUTH_AMOUNT_WITH_TAX", org.jooq.impl.SQLDataType.DECIMAL.precision(18, 6).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0.000000", org.jooq.impl.SQLDataType.DECIMAL)), this, "已认证含税金额\n保留");

    /**
     * The column <code>chenqiguang.t_settlement.CAN_MAKE_INVOICE_AMOUNT_WITHOUT_TAX</code>. 可开正式发票不含税金额
新增
     */
    public final TableField<TSettlementRecord, BigDecimal> CAN_MAKE_INVOICE_AMOUNT_WITHOUT_TAX = createField("CAN_MAKE_INVOICE_AMOUNT_WITHOUT_TAX", org.jooq.impl.SQLDataType.DECIMAL.precision(18, 6).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0.000000", org.jooq.impl.SQLDataType.DECIMAL)), this, "可开正式发票不含税金额\n新增");

    /**
     * The column <code>chenqiguang.t_settlement.ALREADY_INVOICE_AMOUNT_WITHOUT_TAX</code>. 已开正式发票不含税金额
新增
     */
    public final TableField<TSettlementRecord, BigDecimal> ALREADY_INVOICE_AMOUNT_WITHOUT_TAX = createField("ALREADY_INVOICE_AMOUNT_WITHOUT_TAX", org.jooq.impl.SQLDataType.DECIMAL.precision(18, 6).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0.000000", org.jooq.impl.SQLDataType.DECIMAL)), this, "已开正式发票不含税金额\n新增");

    /**
     * The column <code>chenqiguang.t_settlement.ALREADY_AUTH_AMOUNT_WITHOUT_TAX</code>. 已认证不含税金额
新增
     */
    public final TableField<TSettlementRecord, BigDecimal> ALREADY_AUTH_AMOUNT_WITHOUT_TAX = createField("ALREADY_AUTH_AMOUNT_WITHOUT_TAX", org.jooq.impl.SQLDataType.DECIMAL.precision(18, 6).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0.000000", org.jooq.impl.SQLDataType.DECIMAL)), this, "已认证不含税金额\n新增");

    /**
     * The column <code>chenqiguang.t_settlement.CAN_MAKE_INVOICE_TAX_AMOUNT</code>. 可开正式发票税额
新增
     */
    public final TableField<TSettlementRecord, BigDecimal> CAN_MAKE_INVOICE_TAX_AMOUNT = createField("CAN_MAKE_INVOICE_TAX_AMOUNT", org.jooq.impl.SQLDataType.DECIMAL.precision(18, 6).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0.000000", org.jooq.impl.SQLDataType.DECIMAL)), this, "可开正式发票税额\n新增");

    /**
     * The column <code>chenqiguang.t_settlement.ALREADY_INVOICE_TAX_AMOUNT</code>. 已开正式发票税额
新增
     */
    public final TableField<TSettlementRecord, BigDecimal> ALREADY_INVOICE_TAX_AMOUNT = createField("ALREADY_INVOICE_TAX_AMOUNT", org.jooq.impl.SQLDataType.DECIMAL.precision(18, 6).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0.000000", org.jooq.impl.SQLDataType.DECIMAL)), this, "已开正式发票税额\n新增");

    /**
     * The column <code>chenqiguang.t_settlement.ALREADY_AUTH_TAX_AMOUNT</code>. 已认证税额
新增
     */
    public final TableField<TSettlementRecord, BigDecimal> ALREADY_AUTH_TAX_AMOUNT = createField("ALREADY_AUTH_TAX_AMOUNT", org.jooq.impl.SQLDataType.DECIMAL.precision(18, 6).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0.000000", org.jooq.impl.SQLDataType.DECIMAL)), this, "已认证税额\n新增");

    /**
     * The column <code>chenqiguang.t_settlement.ALREADY_PAY_TAX_AMOUNT</code>. 已付款税额
新增
     */
    public final TableField<TSettlementRecord, BigDecimal> ALREADY_PAY_TAX_AMOUNT = createField("ALREADY_PAY_TAX_AMOUNT", org.jooq.impl.SQLDataType.DECIMAL.precision(18, 6).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0.000000", org.jooq.impl.SQLDataType.DECIMAL)), this, "已付款税额\n新增");

    /**
     * The column <code>chenqiguang.t_settlement.ALREADY_PAY_AMOUNT_WITHOUT_TAX</code>. 已付款不含税金额
新增
     */
    public final TableField<TSettlementRecord, BigDecimal> ALREADY_PAY_AMOUNT_WITHOUT_TAX = createField("ALREADY_PAY_AMOUNT_WITHOUT_TAX", org.jooq.impl.SQLDataType.DECIMAL.precision(18, 6).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0.000000", org.jooq.impl.SQLDataType.DECIMAL)), this, "已付款不含税金额\n新增");

    /**
     * The column <code>chenqiguang.t_settlement.ALREADY_PAY_AMOUNT_WIHT_TAX</code>. 已付款含税金额
保留
     */
    public final TableField<TSettlementRecord, BigDecimal> ALREADY_PAY_AMOUNT_WIHT_TAX = createField("ALREADY_PAY_AMOUNT_WIHT_TAX", org.jooq.impl.SQLDataType.DECIMAL.precision(18, 6).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0.000000", org.jooq.impl.SQLDataType.DECIMAL)), this, "已付款含税金额\n保留");

    /**
     * The column <code>chenqiguang.t_settlement.ALREADY_DEPOSE_AMOUNT_WITH_TAX</code>. 已开发票作废含税金额
     */
    public final TableField<TSettlementRecord, BigDecimal> ALREADY_DEPOSE_AMOUNT_WITH_TAX = createField("ALREADY_DEPOSE_AMOUNT_WITH_TAX", org.jooq.impl.SQLDataType.DECIMAL.precision(18, 6).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0.000000", org.jooq.impl.SQLDataType.DECIMAL)), this, "已开发票作废含税金额");

    /**
     * The column <code>chenqiguang.t_settlement.ALREADY_RED_AMOUNT_WITH_TAX</code>. 已开发票红冲含税金额
     */
    public final TableField<TSettlementRecord, BigDecimal> ALREADY_RED_AMOUNT_WITH_TAX = createField("ALREADY_RED_AMOUNT_WITH_TAX", org.jooq.impl.SQLDataType.DECIMAL.precision(18, 6).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0.000000", org.jooq.impl.SQLDataType.DECIMAL)), this, "已开发票红冲含税金额");

    /**
     * The column <code>chenqiguang.t_settlement.DISCOUNT_WITHOUT_TAX</code>. 不含税折扣金额
     */
    public final TableField<TSettlementRecord, BigDecimal> DISCOUNT_WITHOUT_TAX = createField("DISCOUNT_WITHOUT_TAX", org.jooq.impl.SQLDataType.DECIMAL.precision(18, 6).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0.000000", org.jooq.impl.SQLDataType.DECIMAL)), this, "不含税折扣金额");

    /**
     * The column <code>chenqiguang.t_settlement.DISCOUNT_TAX</code>. 折扣税额
     */
    public final TableField<TSettlementRecord, BigDecimal> DISCOUNT_TAX = createField("DISCOUNT_TAX", org.jooq.impl.SQLDataType.DECIMAL.precision(18, 6).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0.000000", org.jooq.impl.SQLDataType.DECIMAL)), this, "折扣税额");

    /**
     * The column <code>chenqiguang.t_settlement.DISCOUNT_WITH_TAX</code>. 含税折扣金额
     */
    public final TableField<TSettlementRecord, BigDecimal> DISCOUNT_WITH_TAX = createField("DISCOUNT_WITH_TAX", org.jooq.impl.SQLDataType.DECIMAL.precision(18, 6).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0.000000", org.jooq.impl.SQLDataType.DECIMAL)), this, "含税折扣金额");

    /**
     * The column <code>chenqiguang.t_settlement.REMARK</code>. 结算单备注
结算单备注上传后不能修改
     */
    public final TableField<TSettlementRecord, String> REMARK = createField("REMARK", org.jooq.impl.SQLDataType.VARCHAR.length(500).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "结算单备注\n结算单备注上传后不能修改");

    /**
     * The column <code>chenqiguang.t_settlement.APPEND_REMARK</code>. 追加说明
新增字段，用于补充结算单备注
     */
    public final TableField<TSettlementRecord, String> APPEND_REMARK = createField("APPEND_REMARK", org.jooq.impl.SQLDataType.VARCHAR.length(500).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "追加说明\n新增字段，用于补充结算单备注");

    /**
     * The column <code>chenqiguang.t_settlement.PRE_INVOICE_NUMS</code>. 预制发票张数
保留不用
     */
    public final TableField<TSettlementRecord, Integer> PRE_INVOICE_NUMS = createField("PRE_INVOICE_NUMS", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "预制发票张数\n保留不用");

    /**
     * The column <code>chenqiguang.t_settlement.CAN_MAKE_INVOICE_NUMS</code>. 待开预制发票张数
新增字段
     */
    public final TableField<TSettlementRecord, Integer> CAN_MAKE_INVOICE_NUMS = createField("CAN_MAKE_INVOICE_NUMS", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "待开预制发票张数\n新增字段");

    /**
     * The column <code>chenqiguang.t_settlement.INVOICE_NUMS</code>. 正式发票张数
新增字段
     */
    public final TableField<TSettlementRecord, Integer> INVOICE_NUMS = createField("INVOICE_NUMS", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "正式发票张数\n新增字段");

    /**
     * The column <code>chenqiguang.t_settlement.RECEIVE_CONFIRM_FLAG</code>. 接收方结算单确认状态
后三个状态都是一样的在双方字段中
     */
    public final TableField<TSettlementRecord, String> RECEIVE_CONFIRM_FLAG = createField("RECEIVE_CONFIRM_FLAG", org.jooq.impl.SQLDataType.VARCHAR.length(2).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "接收方结算单确认状态\n后三个状态都是一样的在双方字段中");

    /**
     * The column <code>chenqiguang.t_settlement.UPLOAD_CONFIRM_FLAG</code>. 上传方结算单确认状态
待确认，有变更，对方确认中，代开票，已作废，已删除
     */
    public final TableField<TSettlementRecord, String> UPLOAD_CONFIRM_FLAG = createField("UPLOAD_CONFIRM_FLAG", org.jooq.impl.SQLDataType.VARCHAR.length(2).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "上传方结算单确认状态\n待确认，有变更，对方确认中，代开票，已作废，已删除");

    /**
     * The column <code>chenqiguang.t_settlement.STATUS</code>. 状态 0-作废  
1-正常  
9-删除
     */
    public final TableField<TSettlementRecord, String> STATUS = createField("STATUS", org.jooq.impl.SQLDataType.VARCHAR.length(2).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "状态 0-作废  \n1-正常  \n9-删除");

    /**
     * The column <code>chenqiguang.t_settlement.ORIGIN_INVOICE_NO</code>. 原发票号码
     */
    public final TableField<TSettlementRecord, String> ORIGIN_INVOICE_NO = createField("ORIGIN_INVOICE_NO", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "原发票号码");

    /**
     * The column <code>chenqiguang.t_settlement.ORIGIN_INVOICE_CODE</code>. 原发票代码
     */
    public final TableField<TSettlementRecord, String> ORIGIN_INVOICE_CODE = createField("ORIGIN_INVOICE_CODE", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "原发票代码");

    /**
     * The column <code>chenqiguang.t_settlement.RED_NOTIFICATION_NO</code>. 红字信息表编号
     */
    public final TableField<TSettlementRecord, String> RED_NOTIFICATION_NO = createField("RED_NOTIFICATION_NO", org.jooq.impl.SQLDataType.VARCHAR.length(40).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "红字信息表编号");

    /**
     * The column <code>chenqiguang.t_settlement.ORDER_NO</code>. 订单号(企业)
     */
    public final TableField<TSettlementRecord, String> ORDER_NO = createField("ORDER_NO", org.jooq.impl.SQLDataType.VARCHAR.length(168).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "订单号(企业)");

    /**
     * The column <code>chenqiguang.t_settlement.CONTRACT_NO</code>. 合同号(企业)
     */
    public final TableField<TSettlementRecord, String> CONTRACT_NO = createField("CONTRACT_NO", org.jooq.impl.SQLDataType.VARCHAR.length(300).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "合同号(企业)");

    /**
     * The column <code>chenqiguang.t_settlement.SYSTEM_ORIG</code>. 系统来源
     */
    public final TableField<TSettlementRecord, String> SYSTEM_ORIG = createField("SYSTEM_ORIG", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "系统来源");

    /**
     * The column <code>chenqiguang.t_settlement.SALES_BILL_NO</code>. 销售单据号
     */
    public final TableField<TSettlementRecord, String> SALES_BILL_NO = createField("SALES_BILL_NO", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "销售单据号");

    /**
     * The column <code>chenqiguang.t_settlement.IS_NEED_AUTH</code>. 其下发票是否需要认证2-不需要1-需要
仅AP结算单使用
     */
    public final TableField<TSettlementRecord, String> IS_NEED_AUTH = createField("IS_NEED_AUTH", org.jooq.impl.SQLDataType.VARCHAR.length(2).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "其下发票是否需要认证2-不需要1-需要\n仅AP结算单使用");

    /**
     * The column <code>chenqiguang.t_settlement.COOPERATE_FLAG</code>. 协同类型(0-非协同；1-协同；)
接口上传导入以票易通平台配置决定
     */
    public final TableField<TSettlementRecord, String> COOPERATE_FLAG = createField("COOPERATE_FLAG", org.jooq.impl.SQLDataType.VARCHAR.length(2).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "协同类型(0-非协同；1-协同；)\n接口上传导入以票易通平台配置决定");

    /**
     * The column <code>chenqiguang.t_settlement.REQUEST_SERIAL_NO</code>. 请求流水号
待确认
     */
    public final TableField<TSettlementRecord, String> REQUEST_SERIAL_NO = createField("REQUEST_SERIAL_NO", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "请求流水号\n待确认");

    /**
     * The column <code>chenqiguang.t_settlement.PURCHASER_EMAIL</code>. 购方邮箱
电票使用
     */
    public final TableField<TSettlementRecord, String> PURCHASER_EMAIL = createField("PURCHASER_EMAIL", org.jooq.impl.SQLDataType.VARCHAR.length(80).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "购方邮箱\n电票使用");

    /**
     * The column <code>chenqiguang.t_settlement.LOGISTICS_STATUS</code>. 物流状态
     */
    public final TableField<TSettlementRecord, String> LOGISTICS_STATUS = createField("LOGISTICS_STATUS", org.jooq.impl.SQLDataType.VARCHAR.length(2).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "物流状态");

    /**
     * The column <code>chenqiguang.t_settlement.CREATE_TIME</code>. 创建时间
     */
    public final TableField<TSettlementRecord, String> CREATE_TIME = createField("CREATE_TIME", org.jooq.impl.SQLDataType.VARCHAR.length(17).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "创建时间");

    /**
     * The column <code>chenqiguang.t_settlement.CREATE_USER_ID</code>. 创建操作账号
     */
    public final TableField<TSettlementRecord, String> CREATE_USER_ID = createField("CREATE_USER_ID", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "创建操作账号");

    /**
     * The column <code>chenqiguang.t_settlement.UPDATE_TIME</code>. 修改时间
     */
    public final TableField<TSettlementRecord, String> UPDATE_TIME = createField("UPDATE_TIME", org.jooq.impl.SQLDataType.VARCHAR.length(17).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "修改时间");

    /**
     * The column <code>chenqiguang.t_settlement.UPDATE_USER_ID</code>. 修改操作账号
     */
    public final TableField<TSettlementRecord, String> UPDATE_USER_ID = createField("UPDATE_USER_ID", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "修改操作账号");

    /**
     * The column <code>chenqiguang.t_settlement.SPECIAL_EXT1</code>. 特殊扩展字段1
     */
    public final TableField<TSettlementRecord, String> SPECIAL_EXT1 = createField("SPECIAL_EXT1", org.jooq.impl.SQLDataType.VARCHAR.length(2).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "特殊扩展字段1");

    /**
     * The column <code>chenqiguang.t_settlement.SPECIAL_EXT2</code>. 特殊扩展字段2
     */
    public final TableField<TSettlementRecord, String> SPECIAL_EXT2 = createField("SPECIAL_EXT2", org.jooq.impl.SQLDataType.VARCHAR.length(10).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "特殊扩展字段2");

    /**
     * The column <code>chenqiguang.t_settlement.EXT1</code>. 扩展字段1
     */
    public final TableField<TSettlementRecord, String> EXT1 = createField("EXT1", org.jooq.impl.SQLDataType.VARCHAR.length(50).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "扩展字段1");

    /**
     * The column <code>chenqiguang.t_settlement.EXT2</code>. 扩展字段2
     */
    public final TableField<TSettlementRecord, String> EXT2 = createField("EXT2", org.jooq.impl.SQLDataType.VARCHAR.length(50).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "扩展字段2");

    /**
     * The column <code>chenqiguang.t_settlement.EXT3</code>. 扩展字段3
     */
    public final TableField<TSettlementRecord, String> EXT3 = createField("EXT3", org.jooq.impl.SQLDataType.VARCHAR.length(50).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "扩展字段3");

    /**
     * The column <code>chenqiguang.t_settlement.EXT4</code>. 扩展字段4
     */
    public final TableField<TSettlementRecord, String> EXT4 = createField("EXT4", org.jooq.impl.SQLDataType.VARCHAR.length(50).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "扩展字段4");

    /**
     * The column <code>chenqiguang.t_settlement.EXT5</code>. 扩展字段5
     */
    public final TableField<TSettlementRecord, String> EXT5 = createField("EXT5", org.jooq.impl.SQLDataType.VARCHAR.length(50).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "扩展字段5");

    /**
     * The column <code>chenqiguang.t_settlement.EXT6</code>. 扩展字段6
     */
    public final TableField<TSettlementRecord, String> EXT6 = createField("EXT6", org.jooq.impl.SQLDataType.VARCHAR.length(50).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "扩展字段6");

    /**
     * The column <code>chenqiguang.t_settlement.EXT7</code>. 扩展字段7
     */
    public final TableField<TSettlementRecord, String> EXT7 = createField("EXT7", org.jooq.impl.SQLDataType.VARCHAR.length(50).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "扩展字段7");

    /**
     * The column <code>chenqiguang.t_settlement.EXT8</code>. 扩展字段8
     */
    public final TableField<TSettlementRecord, String> EXT8 = createField("EXT8", org.jooq.impl.SQLDataType.VARCHAR.length(50).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "扩展字段8");

    /**
     * The column <code>chenqiguang.t_settlement.EXT9</code>. 扩展字段9-占用存放原结算单号
     */
    public final TableField<TSettlementRecord, String> EXT9 = createField("EXT9", org.jooq.impl.SQLDataType.VARCHAR.length(50).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "扩展字段9-占用存放原结算单号");

    /**
     * The column <code>chenqiguang.t_settlement.EXT10</code>. 扩展字段10
     */
    public final TableField<TSettlementRecord, String> EXT10 = createField("EXT10", org.jooq.impl.SQLDataType.VARCHAR.length(50).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "扩展字段10");

    /**
     * The column <code>chenqiguang.t_settlement.UPLOAD_WAY</code>. 上传途径(0:平台1:接口)
     */
    public final TableField<TSettlementRecord, String> UPLOAD_WAY = createField("UPLOAD_WAY", org.jooq.impl.SQLDataType.VARCHAR.length(2).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "上传途径(0:平台1:接口)");

    /**
     * The column <code>chenqiguang.t_settlement.CASHIER_NAME</code>. 收款人姓名
     */
    public final TableField<TSettlementRecord, String> CASHIER_NAME = createField("CASHIER_NAME", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "收款人姓名");

    /**
     * The column <code>chenqiguang.t_settlement.CHECKER_NAME</code>. 复核人姓名
     */
    public final TableField<TSettlementRecord, String> CHECKER_NAME = createField("CHECKER_NAME", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "复核人姓名");

    /**
     * The column <code>chenqiguang.t_settlement.INVOICER_NAME</code>. 开票人姓名
     */
    public final TableField<TSettlementRecord, String> INVOICER_NAME = createField("INVOICER_NAME", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "开票人姓名");

    /**
     * The column <code>chenqiguang.t_settlement.LOCK_FLAG</code>. 锁状态 1-正常 
6-导入封锁
4-主信息变更封锁
5-失效封锁
7-删除封锁
8-生成预制发票封锁
     */
    public final TableField<TSettlementRecord, String> LOCK_FLAG = createField("LOCK_FLAG", org.jooq.impl.SQLDataType.VARCHAR.length(2).defaultValue(org.jooq.impl.DSL.inline("1", org.jooq.impl.SQLDataType.VARCHAR)), this, "锁状态 1-正常 \n6-导入封锁\n4-主信息变更封锁\n5-失效封锁\n7-删除封锁\n8-生成预制发票封锁");

    /**
     * The column <code>chenqiguang.t_settlement.TAX_RATE</code>. 结算单税率，不同税率用逗号隔开
     */
    public final TableField<TSettlementRecord, String> TAX_RATE = createField("TAX_RATE", org.jooq.impl.SQLDataType.VARCHAR.length(200).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "结算单税率，不同税率用逗号隔开");

    /**
     * The column <code>chenqiguang.t_settlement.USEING_STATUS</code>. 1:使用中 0:未使用
     */
    public final TableField<TSettlementRecord, String> USEING_STATUS = createField("USEING_STATUS", org.jooq.impl.SQLDataType.VARCHAR.length(2).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "1:使用中 0:未使用");

    /**
     * The column <code>chenqiguang.t_settlement.PUR_ALREADY_AMOUNT_WITHOUT_TAX</code>.
     */
    public final TableField<TSettlementRecord, BigDecimal> PUR_ALREADY_AMOUNT_WITHOUT_TAX = createField("PUR_ALREADY_AMOUNT_WITHOUT_TAX", org.jooq.impl.SQLDataType.DECIMAL.precision(18, 6).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0.000000", org.jooq.impl.SQLDataType.DECIMAL)), this, "");

    /**
     * The column <code>chenqiguang.t_settlement.PUR_ALREADY_TAX_AMOUNT</code>.
     */
    public final TableField<TSettlementRecord, BigDecimal> PUR_ALREADY_TAX_AMOUNT = createField("PUR_ALREADY_TAX_AMOUNT", org.jooq.impl.SQLDataType.DECIMAL.precision(18, 6).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0.000000", org.jooq.impl.SQLDataType.DECIMAL)), this, "");

    /**
     * The column <code>chenqiguang.t_settlement.PUR_ALREADY_AMOUNT_WITH_TAX</code>.
     */
    public final TableField<TSettlementRecord, BigDecimal> PUR_ALREADY_AMOUNT_WITH_TAX = createField("PUR_ALREADY_AMOUNT_WITH_TAX", org.jooq.impl.SQLDataType.DECIMAL.precision(18, 6).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0.000000", org.jooq.impl.SQLDataType.DECIMAL)), this, "");

    /**
     * The column <code>chenqiguang.t_settlement.PRINT_CONTENT_FLAG</code>. 打印内容标志（0-打印单价和数量 1-不打印单价和数量，默认0）
     */
    public final TableField<TSettlementRecord, String> PRINT_CONTENT_FLAG = createField("PRINT_CONTENT_FLAG", org.jooq.impl.SQLDataType.VARCHAR.length(2), this, "打印内容标志（0-打印单价和数量 1-不打印单价和数量，默认0）");

    /**
     * The column <code>chenqiguang.t_settlement.SELLER_INVOICE_PERSON_INFO_ID</code>. 票面人员信息ID
     */
    public final TableField<TSettlementRecord, Integer> SELLER_INVOICE_PERSON_INFO_ID = createField("SELLER_INVOICE_PERSON_INFO_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "票面人员信息ID");

    /**
     * The column <code>chenqiguang.t_settlement.PUR_MACH_STATUS</code>. 配单状态0-待匹配，1-已匹配
     */
    public final TableField<TSettlementRecord, String> PUR_MACH_STATUS = createField("PUR_MACH_STATUS", org.jooq.impl.SQLDataType.VARCHAR.length(2).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "配单状态0-待匹配，1-已匹配");

    /**
     * The column <code>chenqiguang.t_settlement.RECIVE_USER</code>. 发票开局后自动发送邮件的邮箱
     */
    public final TableField<TSettlementRecord, String> RECIVE_USER = createField("RECIVE_USER", org.jooq.impl.SQLDataType.VARCHAR.length(250).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "发票开局后自动发送邮件的邮箱");

    /**
     * Create a <code>chenqiguang.t_settlement</code> table reference
     */
    public TSettlement() {
        this("t_settlement", null);
    }

    /**
     * Create an aliased <code>chenqiguang.t_settlement</code> table reference
     */
    public TSettlement(String alias) {
        this(alias, T_SETTLEMENT);
    }

    private TSettlement(String alias, Table<TSettlementRecord> aliased) {
        this(alias, aliased, null);
    }

    private TSettlement(String alias, Table<TSettlementRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "结算单表");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Chenqiguang.CHENQIGUANG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TSettlementRecord> getPrimaryKey() {
        return Keys.KEY_T_SETTLEMENT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TSettlementRecord>> getKeys() {
        return Arrays.<UniqueKey<TSettlementRecord>>asList(Keys.KEY_T_SETTLEMENT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSettlement as(String alias) {
        return new TSettlement(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TSettlement rename(String name) {
        return new TSettlement(name, null);
    }
}
